### ISSUE TITLE
Option to have navbar to use the full webpage width

### ISSUE THREAD

**Issue by NovaViper** [LazeMSS/OctoPrint-UICustomizer#10]
It's a bit odd that the rest of the page expands but the navigation bar doesn't (Shown below)
![image](https://user-images.githubusercontent.com/7191115/100925345-8033e700-34a7-11eb-8b63-3b29117c18a6.png)

The navbar should also use the full width of the browser just like the rest of the UI does

**Comment by LazeMSS** [comment]
Strange, what browser and os?
What settings do you have turned on, fixed header?

**Comment by Guilouz** [comment]
Same here, I use Chrome on MacOS. Fixed Header or not same issue.

When installing OctoPrint-WideScreen nav bar is ok

**Comment by NovaViper** [comment]
> Strange, what browser and os?
> What settings do you have turned on, fixed header?

The browser is Vivaldi, and the OS is EndeavourOS KDE. I have all of the default settings on

**Comment by LazeMSS** [comment]
Does this page behave the same:
https://getbootstrap.com/2.3.2/examples/fluid.html or is that full width?

**Comment by NovaViper** [comment]
> Does this page behave the same:
> https://getbootstrap.com/2.3.2/examples/fluid.html or is that full width?

It's full width there

**Comment by LazeMSS** [comment]
> > Does this page behave the same:
> > https://getbootstrap.com/2.3.2/examples/fluid.html or is that full width?
> 
> It's full width there

Try running the following in a developer console in your browser:
$('#navbar div.navbar-inner a.btn-navbar').remove();

Then run this:
$('#navbar > div.navbar-inner.default > div:first').prepend('<a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".UICMainMenu"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a>');

**Comment by NovaViper** [comment]
Um.. how do I run it in the developer console? It's the same developer console as for Chrome (since the browser is based on Chrome)

**Comment by LazeMSS** [comment]
> Um.. how do I run it in the developer console? It's the same developer console as for Chrome (since the browser is based on Chrome)

https://help.vivaldi.com/article/developer-tools/

**Comment by LazeMSS** [comment]
Should be now fixed - please update and test :)

**Comment by Guilouz** [comment]
No not working, same issue with latest update.

<img width="2560" alt="Capture d’écran 2020-12-06 à 16 34 33" src="https://user-images.githubusercontent.com/12702322/101284598-243bcc00-37e1-11eb-9f00-6fc9fda07a23.png">

**Comment by LazeMSS** [comment]
I'm sorry to say but there must be a plugin installed that messes with your installation.
This is how it looks in Vilvadi for me:
![image](https://user-images.githubusercontent.com/69049371/101287887-535b3900-37f3-11eb-832e-80070f7b243b.png)

**Comment by NovaViper** [comment]
It's not working for me either, even when I only have UI Customizer loaded

**Comment by Guilouz** [comment]
> I'm sorry to say but there must be a plugin installed that messes with your installation.
> This is how it looks in Vilvadi for me:
> ![image](https://user-images.githubusercontent.com/69049371/101287887-535b3900-37f3-11eb-832e-80070f7b243b.png)

I use Google Chrome and it's working when I use Octoprint widescreen plugin so I think there is a mistake in your code.

Without Widescreen plugin, only UICustomizer : 

<img width="2560" alt="Capture d’écran 2020-12-06 à 20 20 26" src="https://user-images.githubusercontent.com/12702322/101290157-c6b77780-3800-11eb-8feb-e01e06b3ab62.png">

With Widescreen plugin + UICustomizer : 

<img width="2560" alt="Capture d’écran 2020-12-06 à 20 22 19" src="https://user-images.githubusercontent.com/12702322/101290172-d0d97600-3800-11eb-930f-d97bdf9fc6ef.png">

**Comment by LazeMSS** [comment]
I will look ASAP

**Comment by LazeMSS** [comment]
I have looked and looked - it must be related in one of the plugins. The way the Widescreen plugin does the widescreen is not pretty. I would rather find the real source to the problem and fix it together with the author of that plugin. I know it sounds weird but that way my hack wont later on destroy somebody elses plugins - trying to keep it clean.

**Comment by LazeMSS** [comment]
> It's not working for me either, even when I only have UI Customizer loaded

So you dont have widescreen - even when you just have UI Customizer loaded as 3rd party plugin? In which browsers?

**Comment by knopancakes** [comment]
FYI, I am seeing the same behavior in Firefox 83.0 with OctoPrinti 1.5.1 and OctoPrint-UICustomizer 0.1.0.5

**Comment by LazeMSS** [comment]
> FYI, I am seeing the same behavior in Firefox 83.0 with OctoPrinti 1.5.1 and OctoPrint-UICustomizer 0.1.0.5

Could you post a list of plugins you are using?

**Comment by NovaViper** [comment]
> > It's not working for me either, even when I only have UI Customizer loaded
> 
> So it does not work in full widescreen? - even when you just have UI Customizer loaded as 3rd party plugin? In which browsers? Have you tried Chrome.

It didn't work in either maximixed mode or full screen, tried it on multiple computers (one with Chrome and one with Vivaldi), all have the same issue.

**Comment by LazeMSS** [comment]
> > > It's not working for me either, even when I only have UI Customizer loaded
> > 
> > 
> > So it does not work in full widescreen? - even when you just have UI Customizer loaded as 3rd party plugin? In which browsers? Have you tried Chrome.
> 
> It didn't work in either maximixed mode or full screen, tried it on multiple computers (one with Chrome and one with Vivaldi), all have the same issue.

Can you post a list of plugins?

**Comment by knopancakes** [comment]
Full list of plugins running on my setup:
DisplayLayerProgress
Octolapse
PrintTimeGenius
Printer Dialogs
Printer Notifications
UI Customizer
Virtual Printer

**Comment by LazeMSS** [comment]
> Printer Dialogs
> Printer Notifications

Cant find these plugins

**Comment by NovaViper** [comment]
> > > > It's not working for me either, even when I only have UI Customizer loaded
> > > 
> > > 
> > > So it does not work in full widescreen? - even when you just have UI Customizer loaded as 3rd party plugin? In which browsers? Have you tried Chrome.
> > 
> > 
> > It didn't work in either maximixed mode or full screen, tried it on multiple computers (one with Chrome and one with Vivaldi), all have the same issue.
> 
> Can you post a list of plugins?

I ran it after uninstalling all of the plugins

**Comment by LazeMSS** [comment]
> > > > > It's not working for me either, even when I only have UI Customizer loaded
> > > > 
> > > > 
> > > > So it does not work in full widescreen? - even when you just have UI Customizer loaded as 3rd party plugin? In which browsers? Have you tried Chrome.
> > > 
> > > 
> > > It didn't work in either maximixed mode or full screen, tried it on multiple computers (one with Chrome and one with Vivaldi), all have the same issue.
> > 
> > 
> > Can you post a list of plugins?
> 
> I ran it after uninstalling all of the plugins

So you have no other than my plugin installed as a 3rd party plugin?

**Comment by knopancakes** [comment]
> 
> 
> > Printer Dialogs
> > Printer Notifications
> 
> Cant find these plugins

Those are built in, not 3rd party

**Comment by NovaViper** [comment]
> > > > > > It's not working for me either, even when I only have UI Customizer loaded
> > > > > 
> > > > > 
> > > > > So it does not work in full widescreen? - even when you just have UI Customizer loaded as 3rd party plugin? In which browsers? Have you tried Chrome.
> > > > 
> > > > 
> > > > It didn't work in either maximixed mode or full screen, tried it on multiple computers (one with Chrome and one with Vivaldi), all have the same issue.
> > > 
> > > 
> > > Can you post a list of plugins?
> > 
> > 
> > I ran it after uninstalling all of the plugins
> 
> So you have no other than my plugin installed as a 3rd party plugin?

Yes

**Comment by LazeMSS** [comment]
> > 
> > So you have no other than my plugin installed as a 3rd party plugin?
> 
> Yes

And still it does not work - I cant understand it - if anyone of you guys are willing 5 minutes with teamviewer would help alot

**Comment by knopancakes** [comment]
I lied to you all about the plugins I had installed. The original comment has been edited to reflect only 3rd party plugins, including the Fullscreen Plugin I had missed.

**Comment by LazeMSS** [comment]
> Fullscreen Plugin

Does it work uninstalling it - is it the fullscreen webcam?

**Comment by knopancakes** [comment]
Yes, the Fullscreen Plugin is the webcam one. Disabling the Fullscreen Plugin resolves the oddities with the webcam widget, but not the top bar
![image](https://user-images.githubusercontent.com/16746364/101416594-30468d00-38b8-11eb-8f3b-e13e09ea0fad.png)

**Comment by LazeMSS** [comment]
> Yes, the Fullscreen Plugin is the webcam one. Disabling the Fullscreen Plugin resolves the oddities with the webcam widget, but not the top bar

I will try your list now

**Comment by knopancakes** [comment]
I'll have to work on getting teamviewer installed. Got some other things I need to take care of first. Among them, hungry cats to feed.

Re: python, that also jumped out at me... @NovaViper is also running 2.7, but @Guilouz has 3.7 and also experiences the issue.

Settings:
![image](https://user-images.githubusercontent.com/16746364/101417664-19a13580-38ba-11eb-94ac-184dd4b6f88e.png)

![image](https://user-images.githubusercontent.com/16746364/101417693-2a51ab80-38ba-11eb-90c6-6987e0a8ead3.png)

![image](https://user-images.githubusercontent.com/16746364/101417711-38073100-38ba-11eb-99f7-28618040875f.png)

**Comment by LazeMSS** [comment]
Thanks - if you have the time try running this in your browsers console:
`  $('#navbar > div.navbar-inner > div:first').removeClass("container").addClass("container-fluid").removeAttr("style","");
   $('div.UICMainCont').removeClass("container").addClass("container-fluid");
    $('div.UICMainCont > div.row:first').removeClass("row").addClass("row-fluid");`

**Comment by Guilouz** [comment]
> $('#navbar > div.navbar-inner > div:first').removeClass("container").addClass("container-fluid").removeAttr("style",""); $('div.UICMainCont').removeClass("container").addClass("container-fluid"); $('div.UICMainCont > div.row:first').removeClass("row").addClass("row-fluid");

With this in browser console it's working.

**Comment by LazeMSS** [comment]
> > $('#navbar > div.navbar-inner > div:first').removeClass("container").addClass("container-fluid").removeAttr("style",""); $('div.UICMainCont').removeClass("container").addClass("container-fluid"); $('div.UICMainCont > div.row:first').removeClass("row").addClass("row-fluid");
> 
> With this in browser console it's working.

Thanks - I knew somewhere something was tampering with the layout - this is included in the next version then!

**Comment by knopancakes** [comment]
Works for me too, thanks!

**Comment by LazeMSS** [comment]
Thanks everyone for testing.

I will try and get the new release out soon.

**Comment by LazeMSS** [comment]
Please test to confirm its fixed in the latest version 0.1.0.9

**Comment by Guilouz** [comment]
> Please test to confirm its fixed in the latest version 0.1.0.9

Working with latest release. Thanks.

**Comment by NovaViper** [comment]
It's works in the latest version for me as well! Thanks :D
