### ISSUE TITLE
Combine Controls (X, Y, Z, E) with Temp Controls

### ISSUE THREAD

**Issue by wlbillmartin** [LazeMSS/OctoPrint-UICustomizer#102]
Idea: Combine all commonly used controls together. See Pics:
Currently:
![Current](https://user-images.githubusercontent.com/78445656/109340453-e4074b00-781d-11eb-8078-30b7c7156108.png)
Idea:
![Idea](https://user-images.githubusercontent.com/78445656/109340481-ebc6ef80-781d-11eb-8527-1f872cf7009e.png)

**Comment by LazeMSS** [comment]
The same as: https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/30 ?
