### ISSUE TITLE
PrettyGCode not displaying correctly in fullscreen

### ISSUE THREAD

**Issue by RyanStarr** [LazeMSS/OctoPrint-UICustomizer#103]
### PrettyGCode works fine when windowed.

![windowed](https://user-images.githubusercontent.com/16529414/109399244-9f70d200-7939-11eb-82b9-2deb1a0d19ae.png) 

### But when you select the option to make it full screen. the information buttons are slightly hidden under the navbar and completely hidden under the footer bar. 

![full screen](https://user-images.githubusercontent.com/16529414/109399248-a26bc280-7939-11eb-83b1-e86d53c59233.png)

#### From what I can tell it's when the browser window gets too wide that causes the issue. 4:3 size is fine, 16:9 and the icons are blocked.

![full screen with narrower browser](https://user-images.githubusercontent.com/16529414/109399249-a4ce1c80-7939-11eb-97ba-7802c8666a7c.png)

**Comment by LazeMSS** [comment]
Yes that's going to be hard to fix due to the way that plugin goes into "fullscreen" mode. I might look later for now I won't fix it.
