### ISSUE TITLE
Conflict with plugin PrettyGCode

### ISSUE THREAD

**Issue by Fank** [LazeMSS/OctoPrint-UICustomizer#105]
Plugin: https://plugins.octoprint.org/plugins/prettygcode/

Since using this plugin i have issues that the fullscreen option is not working correctly anymore, there are still bars top, bottom and right side:
![192 168 178 29_](https://user-images.githubusercontent.com/1900106/109880014-addf2680-7c76-11eb-9644-ebaf96291b73.png)

But everything should be hidden.
There is a leave fullscreen button bottom right, which can't be accessed.

**Comment by LazeMSS** [comment]
I think this should be reported on PrettyGCode plugin code - the fixed footer/header and using standard bootstrap way of making fixed header/footer. You can also just disable the fixed header/footer in my plugin.
