### ISSUE TITLE
Latest 1.5.4 doesn't work right

### ISSUE THREAD

**Issue by mbourque** [LazeMSS/OctoPrint-UICustomizer#107]
After I installed, my three column layout was now just one. Had to roll back the changes. I am using Chrome on OSX.

**Comment by LazeMSS** [comment]
So it just broke after updating?

**Comment by LazeMSS** [comment]
Can you maybe look in your developer console and look for errors there?

**Comment by mbourque** [comment]
I will try again, I reverted back but should had captured more info for you.

**Comment by LazeMSS** [comment]
did you revert back to the old version?

**Comment by mbourque** [comment]
Yes

**Comment by mbourque** [comment]
After my print job finishes I will do it all again and send you screenshots and any errors.

**Comment by LazeMSS** [comment]
okay if you try and upgrade let me know and try have a look in the developer console - nothing regarding layout should have happend but there might be a javascript errror causing it all to fail - do you run themify or use any of the colors of octorprint apperance.

**Comment by reclaimer5146** [comment]
Can confirm, themeify breaks it. I disabled themeify and it fixed it. Then I enabled again and it broke it again.

What do you need from me? I don't need to downgrade as I have nothing printing right now.

**Comment by LazeMSS** [comment]
I will try installing themify

**Comment by LazeMSS** [comment]
Thanks

**Comment by LazeMSS** [comment]
@reclaimer5146  do you have any custom css in themify?

**Comment by Hobby4life** [comment]
> Can confirm, themeify breaks it. I disabled themeify and it fixed it. Then I enabled again and it broke it again.
> 
> What do you need from me? I don't need to downgrade as I have nothing printing right now.

I gues the otherway arround.... UICustomizer broke Themify.
Both worked in harmony before 1.5.4 ;-)

**Comment by LazeMSS** [comment]
:)

**Comment by Hobby4life** [comment]
LazeMSS wil fix this.. I know he will :-)

**Comment by LazeMSS** [comment]
Yes bug found 🥇

**Comment by LazeMSS** [comment]
Fixed and released.

**Comment by LazeMSS** [comment]
@Hobby4life , @mbourque  and @reclaimer5146  why would anyone run UI Customizer together with Themify 😛

**Comment by reclaimer5146** [comment]
@LazeMSS Honestly, I only installed UI Customizer and it laid out perfectly so I didn't mess with Themeify. But now that I'm messing with it, I'll remove Themeify 😛

**Comment by mbourque** [comment]
> @Hobby4life , @mbourque and @reclaimer5146 why would anyone run UI Customizer together with Themify 😛

Good question. Maybe I don't need both now that you added themes.

**Comment by Hobby4life** [comment]
Thanks for the fix  :-) 👍
