### ISSUE TITLE
Main tabs not going full width

### ISSUE THREAD

**Issue by LordCorellon** [LazeMSS/OctoPrint-UICustomizer#11]
I recently installed the UI customizer and sadly it is unusable all the other main tabs  do not stretch full width.

The most noticeable is the terminal tab which will only take up a 1/3rd of the middle panel.   Panel is set up for width 6 but the terminal output is only as wide as the left panel (currently set for width two)

**Comment by LazeMSS** [comment]
Could you provide more information, browser, os and maybe a screenshot

**Comment by LordCorellon** [comment]
![Terminal Small](https://user-images.githubusercontent.com/8769496/101206171-bce51700-363c-11eb-852b-4eb3d79eccc6.png)
Windows 10 - Ver 2004 - Build 19401.572
Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by LordCorellon** [comment]
Plugin List:
Active Filters Extended (0.1.0)
Arc-Welder (1.0.0+u.bb71e8f)
Bed Visualizer (1.0.0)
BLTouch Plugin (0.3.4)
Change Filament Plugin (0.3.1)
Detailed Progress (0.2.6)
Enclosure Plugin (4.13.1)
ipOnConnect (0.2.4)
Marlin EEPROM Editor (2.0.0)
Multi Line Terminal (0.1.5)
PrintTimeGenius Plugin (2.2.6)
ProgressBasedOntime Plugin (0.1.6)
Simple Emergency Stop (1.0.4)
UI Customizer (0.1.0.0)

I did have the widescreen plugin and consolidated temp and control installed prior to UI Customizer but had uninstalled them

**Comment by LazeMSS** [comment]
Thats strange im running an almost identical setup - windows 10 and chrome 87. I cant recreate the problems your having - this is how it looks on my pc:
![image](https://user-images.githubusercontent.com/69049371/101262666-b213aa80-3740-11eb-987f-99fe3d495dad.png)

Are you sure you have the rows/colums setup to give a total of 12?
Also maybe try disabling: "Multi Line Terminal" plugin.

Widescreen plugin should NOT be installed together with UI Customizer. Maybe I should add a warning about it.

Im looking into the  consolidated temp and control plugins - they do manipulate alot with the layout and more similar to my plugin.

**Comment by LordCorellon** [comment]
The total is 12 for sure, 3+6+3.

Multi-line terminal works fine, the issue is completely within the consolidated temp and control plug, when I completely uninstall it (and clear data) then the issue goes away, if it's just disabled or uninstalled (without clearing data) then every tab gets squashed.

**Comment by LazeMSS** [comment]
Yes im looking into it now - there is a problem - im fixing it.

**Comment by LazeMSS** [comment]
Try pressing F12 (developer console) in Chrome and paste the following into the console:
`  $('div.page-container').css({'min-width':''});
                $('div.footer').css({'padding-left':'','padding-right':''});
                $('div.UICMainCont > div:first').css({'margin-left':'','padding-right':''});
                $('div.UICMainCont').removeClass('row-fluid');`

**Comment by LordCorellon** [comment]
When I run it, it seems to do the opposite, makes everything in the middle frame squish about 10% more to the left.

**Comment by LazeMSS** [comment]
Can you post a screenshot of your settings for consolidated ?

It might be easier to implement it's functionality into my plugin instead of working around these problems 🙈

**Comment by LordCorellon** [comment]
![Consolidated](https://user-images.githubusercontent.com/8769496/101265969-128ef180-3719-11eb-8866-14fc2ff084ae.png)

Tried with and without nav bar resize enabled

**Comment by LazeMSS** [comment]
Ahh you don't have themify. I can see the control plugin have different behaviour for this. I will spend more time investigating tomorrow. 

Is the only purpose of the control plugin to join the temperature and controls onto one tab?

**Comment by LordCorellon** [comment]
Pretty much what I use it for, I always hated having to switch tabs when changing filament or adjusting offsets.  In fact I would love if the terminal could be combined on the same screen as well and hoped a plugin might do so later.

I'm hoping one day Octoprint moves to a modular sort of layout (If your familiar with OpnSense I like the dashboard setup) where you can specify columns width (like your plugin) but drag and drop "Widgets" to each area to arrange in the order you'd like

**Comment by LazeMSS** [comment]
Should be now fixed - please update and test :)

**Comment by Guilouz** [comment]
No not working, same issue with latest update

<img width="2560" alt="Capture d’écran 2020-12-06 à 16 34 33" src="https://user-images.githubusercontent.com/12702322/101284574-f191d380-37e0-11eb-99be-1271cc56d525.png">

**Comment by LazeMSS** [comment]
@LordCorellon  can you confirm if its working?

**Comment by Guilouz** [comment]
There is issue with full screen. Look search bar

With UICustomizer :

<img width="2560" alt="Capture d’écran 2020-12-07 à 20 14 59" src="https://user-images.githubusercontent.com/12702322/101394608-11042b80-38c9-11eb-85ea-a9c2dd36da3b.png">

With Widescreen plugin all is ok : 

<img width="2560" alt="Capture d’écran 2020-12-07 à 20 15 12" src="https://user-images.githubusercontent.com/12702322/101394655-1feade00-38c9-11eb-9a2f-6835060095b4.png">

**Comment by LazeMSS** [comment]
> There is issue with full screen. Look search bar
> 
> With UICustomizer :
> 
> <img alt="Capture d’écran 2020-12-07 à 20 14 59" width="2000" src="https://user-images.githubusercontent.com/12702322/101394608-11042b80-38c9-11eb-85ea-a9c2dd36da3b.png">
> 
> With Widescreen plugin all is ok :
> 
> <img alt="Capture d’écran 2020-12-07 à 20 15 12" width="2000" src="https://user-images.githubusercontent.com/12702322/101394655-1feade00-38c9-11eb-9a2f-6835060095b4.png">

Yes because widescreen plugin forces that - I would like to avoid that to keep the UI compliant to normal way of doing things. But this bug report is about the main tabs not showing full width when using "consolidated temp" plugin

**Comment by LordCorellon** [comment]
@LazeMSS I can confirm the latest release has fixed the compatibility issue with Consolidated Temp and Control.   Works both in vertical and horizontal arrangements now.

Even better with the wider main tab the control fits perfectly in  horizontal mode without having to scroll down.

Thank you very much

**Comment by LazeMSS** [comment]
> @LazeMSS I can confirm the latest release has fixed the compatibility issue with Consolidated Temp and Control. Works both in vertical and horizontal arrangements now.
> 
> Even better with the wider main tab the control fits perfectly in horizontal mode without having to scroll down.
> 
> Thank you very much

Thanks - I have made a couple of improvements in the next aswell.

**Comment by Guilouz** [comment]
> > There is issue with full screen. Look search bar
> 
> Yes because widescreen plugin forces that - I would like to avoid that to keep the UI compliant to normal way of doing things. But this bug report is about the main tabs not showing full width when using "consolidated temp" plugin.
> 
> Edit:
> Ahh noticed the search bar now - sorry but that when you have disabled "responsive/mobile" mode - I would not recommend turning that off - but I have a fix ready

Yes but I prefer the old settings panel on the left, that's why I have disable it.

**Comment by LazeMSS** [comment]
> > > There is issue with full screen. Look search bar
> > 
> > 
> > Yes because widescreen plugin forces that - I would like to avoid that to keep the UI compliant to normal way of doing things. But this bug report is about the main tabs not showing full width when using "consolidated temp" plugin.
> > Edit:
> > Ahh noticed the search bar now - sorry but that when you have disabled "responsive/mobile" mode - I would not recommend turning that off - but I have a fix ready
> 
> Yes but I prefer the old settings panel on the left, that's why I have disable it. Maybe an option to choose it or not ?

Only way to have a settings menu that works on small screens :(
