### ISSUE TITLE
Top bar background not showing.

### ISSUE THREAD

**Issue by Bob90** [LazeMSS/OctoPrint-UICustomizer#111]
Hi,

Firstly, what a great UI and Top Temp having customizable tabs is so helpful.

My layout has a missing background image as attached. And I haven't been able to get it appear.
![UICust](https://user-images.githubusercontent.com/1275124/110216815-0f86d700-7ea9-11eb-813c-de02dfef9b49.png)

Do you know what I can do?

I have ArcWelder, Bed Vizualiser, Custom Control Editor, Firmware Check, M73 Progress, OctoKlipper, PrintTimeGenius Plugin, Printer Diagnostics, Printer Notifications, Top Temp and Virtual Printer installed.

At installation I had: TouchUI, Tab Order, Consolidate Temp Control installed. I've disabled them since installing your plugin.

**Comment by LazeMSS** [comment]
Have you looked in settings > appearance? Should look like something I have attached
And what theme are you using?

![Screenshot_20210306-230558_Chrome Beta](https://user-images.githubusercontent.com/69049371/110222164-98653900-7ed0-11eb-984a-fb60a6c03dea.png)

**Comment by LazeMSS** [comment]
@Bob90 ???

**Comment by Bob90** [comment]
Hi LazeMSS,

Sorry, this was it. Thank you.

I don't remeeber me doing it. Could another plugin change this not revert on install/unload?
