### ISSUE TITLE
Request: gcode viewer

### ISSUE THREAD

**Issue by maclakey** [LazeMSS/OctoPrint-UICustomizer#112]
I don't see any way to center the gcode viewer... is that a thing I can do?

**Comment by LazeMSS** [comment]
Yes set it in the main gcode viewer settings below the view.

![image](https://user-images.githubusercontent.com/69049371/110841455-2d3bae00-82a6-11eb-8b08-8126ab09a6f1.png)

**Comment by maclakey** [comment]
thanks for making me feel smart.  HAHAH
