### ISSUE TITLE
Navbar shows a checkerboard / grey pattern when using themes (armbian - OPi)

### ISSUE THREAD

**Issue by v-abt** [LazeMSS/OctoPrint-UICustomizer#114]
Hi,
I don't know if this is the right place to post this issue or if this may belong into to the themes repo (just let me know, if you want it to be moved).
I'm using your plugin on an armbian machine (OrangePi +2E) and have some weird problems when using themes:
on all themes, escept "blue moon", the navbar gets a grey checkerboard pattern as if something is missing.
![grafik](https://user-images.githubusercontent.com/66995168/111129509-732e9580-8576-11eb-90aa-34ea1302169c.png)

additionally the prusa tribute theme messes up the button layout in the connection panel:
![grafik](https://user-images.githubusercontent.com/66995168/111129632-99eccc00-8576-11eb-8842-28f98c176057.png)

are there any additional packages necessary to get this plugin working on armbian?
The issue seems to be browser independent (navbar looks the same in the latest firefox, chrome and edge browsers and even on mobile chrome)
[octoprint.log](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/6140174/octoprint.log)

**Comment by LazeMSS** [comment]
Have you enabled the transparent options under settings > OctoPrint   > Appearance?

If so disable it

**Comment by v-abt** [comment]
Yes I had, disabling it fixed the navbar. Thanks a lot! 

The "Prusa Tribute" theme still has that weirdly placed abort button. 
As it is the only broken theme, I guess there is something wrong with it / conflicting with the preheat and/or inline confirm button.

I'm going to close this ticket now.
