### ISSUE TITLE
Plugins incompatible

### ISSUE THREAD

**Issue by Ruissilva** [LazeMSS/OctoPrint-UICustomizer#118]
There is a problem between UI Customizer and Octorelay. UI customizer always shows all of the Octorelay icons R1 to R8 and does not show the icons.

**Comment by LazeMSS** [comment]
I will test

**Comment by Ruissilva** [comment]
Just found the problem. The confict was between smart filament sensor and Octorelay. You can close the issue. Thank you

**Comment by LazeMSS** [comment]
Thanks
