### ISSUE TITLE
Break fix version not working any longer.

### ISSUE THREAD

**Issue by LMS0815** [LazeMSS/OctoPrint-UICustomizer#12]
After Updating to the new - fixed - version, the widgets are not moved to the window they should.

`M117 History` should be on the right panel, but it is still left.

![image](https://user-images.githubusercontent.com/8235214/101165750-79d47500-3637-11eb-8db4-ba08c2062321.png)

**Comment by LazeMSS** [comment]
Do you have a link to the plugin?

**Comment by LMS0815** [comment]
See: https://github.com/jneilliii/OctoPrint-M117PopUp

**Comment by LMS0815** [comment]
Seems to be some broken install at my test system.
Sorry.
