### ISSUE TITLE
Layout width exceeds 12

### ISSUE THREAD

**Issue by seppelicous** [LazeMSS/OctoPrint-UICustomizer#120]
Hi,
the layout must not exceed 12 but it does anyway. I set the width to Left 3, Center 5 and Right 4. It works for a few hours, but then, I do not know why, the width of the center changes automatically to "6" and exceeds the value 12. 
This results in a vertically aligned layout.

kind regards,
Sebastian

<img width="899" alt="Bildschirmfoto 2021-03-25 um 07 14 45" src="https://user-images.githubusercontent.com/34340436/112427551-0ebfc300-8d3a-11eb-98ca-1b436a07cba2.png">

**Comment by LazeMSS** [comment]
Thats really strange. I will test asap

**Comment by seppelicous** [comment]
I just uninstalled the Job History Plugin and after reboot the layout is still as expected. Sounds even more strange

**Comment by LazeMSS** [comment]
The settings in the "Layout" settings should be static so it should never be able to be 13 :(
Do you mean the Job History Plugin was making the broken layout?

**Comment by seppelicous** [comment]
<img width="899" alt="Bildschirmfoto 2021-03-25 um 07 14 45" src="https://user-images.githubusercontent.com/34340436/112499853-2887f700-8d88-11eb-9ef7-0d558a28d958.png">
Okay after restart, the layout is broken again. Layout ist again 3+6+4 - that is weird.
Should I reinstall the plugin?

**Comment by LazeMSS** [comment]
yes or just clear plugin data - thats easier

**Comment by LazeMSS** [comment]
I will write fail check to prevent this from happening.

**Comment by LazeMSS** [comment]
Closing - should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.6
