### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Revel8804** [LazeMSS/OctoPrint-UICustomizer#121]
for the Custom CSS... how do i use it....

i have tried the following. I am not sure what I need to put in there.

`UICfixedHeader UICfixedFooter UICResponsiveMode UICPreviewON {
background-color: #ff69b4
}`

`background-color: #ff69b4`

`#navbar .navbar-inner {
    background-color: #ff69b4;
}`

`.navbar-inner {
    background-color: #ff69b4;
}`

**Comment by LazeMSS** [comment]
Not sure what you want - do you want a pink background color on the top and bottom bars?

```
#navbar .navbar-inner,.footer .navbar-inner{
    background-color: #ff69b4 !important;
    background-image:none;
}

```

Then this should work...

**Comment by LazeMSS** [comment]
It not working then reopen - thanks.
