### ISSUE TITLE
Full screen camera view show ETA

### ISSUE THREAD

**Issue by TheShanMan** [LazeMSS/OctoPrint-UICustomizer#122]
The full screen camera view overlays some textual information. Right now that includes time remaining. I would prefer an ETA, either replacing time remaining or in addition to it.

**Comment by LazeMSS** [comment]
You can drag the overlay but yes information on the overlay is planned

**Comment by LazeMSS** [comment]
Just added now:
Printer state, Filename, Percentage completion, Print time elapsed and left, Tool0 temp, Bed temp, Z-height
