### ISSUE TITLE
File list exceds length

### ISSUE THREAD

**Issue by EddyMI3d** [LazeMSS/OctoPrint-UICustomizer#123]
Hello! 
First a big thanks for that fine plugin.
With my two installations, the file list exceeds the vertical size:

![grafik](https://user-images.githubusercontent.com/8533327/113177753-26251180-924e-11eb-88c0-94ba9c41ffa5.png)

One or two less entries would do the trick. Or a manual setting for the shown entries in the list.

Or have I overseen something?

**Comment by LazeMSS** [comment]
I thing is caused by the thumbnail plugin - but there should always be a scrollbar - are you using the "Maximize Files height" option?
