### ISSUE TITLE
All Grey Theme

### ISSUE THREAD

**Issue by mac-za** [LazeMSS/OctoPrint-UICustomizer#126]
Morning

I could not find the correct forum for a suggestion:

Could you assist with an all grey theme? The cyborg theme partially works, but I would like it if the temperature graph background could also be grey. Unless I am missing something for tweaking the colour myself?

Thanks in advance

Kenneth

**Comment by LazeMSS** [comment]
There are more themes coming - promise :)

**Comment by LazeMSS** [comment]
ohh the temperature graph in the cyborg theme - that should already be black/dark - or is it in the toptemp plugin?

**Comment by mac-za** [comment]
Hi, yes

If the temp graph can also be grey please.


I like the "dark mode" and the temp graph is very bright otherwise.

Thanks for the great work

Kenneth

**Comment by LazeMSS** [comment]
Can you post a screenshot?

**Comment by mac-za** [comment]
Hi
Will do so a bit later tonight. Thanks

**Comment by mac-za** [comment]
Hi

I re-activated the plugin to show you the white background I was
experiencing on the Temperature Graph.

I already had the Themeify plugin installed.

The graph now has a grey background.

I have select the Cyborg and Slate themes with the same results,

Kind Regards

Kenneth

**Comment by LazeMSS** [comment]
@mac-za themeify does not apply themes to the popovers and also might have problems together with my plugin.

Could you try using one the UI Customizer themes with Themify disabled?

**Comment by mac-za** [comment]
Hi

I'll look at that tomorrow morning

Thanks for your replies.

**Comment by mac-za** [comment]
Morning

I have disabled the Themeify app.

I selected the cyborg theme and have attached a screenshot

[image: image.png]

Would it be possible to have a grey background?


I have re-enabled Themeify and this is the result

[image: image.png]

Thanks again for your responses

Kenneth

**Comment by LazeMSS** [comment]
You cant include images in email replies :(

**Comment by mac-za** [comment]
Hi

I've added two images two my google drive folder

The link is below

https://drive.google.com/drive/folders/1nrvpXBdz8CwsgfVWE4hvabGobbrMSr2y?usp=sharing

**Comment by LazeMSS** [comment]
You are using some kind of plugin for the graphs - that not the standard temperature graphs.

**Comment by LazeMSS** [comment]
@mac-za  my guess is this plugin:
https://plugins.octoprint.org/plugins/tempsgraph/

My themes don't currently support this - sorry

**Comment by mac-za** [comment]
Hi,

I did not reply.

I am using the temps graph plugin.

Thanks again for your help

Kenneth

**Comment by mac-za** [comment]
Hi again

Meant to say, sorry for not replying earlier.

Thanks again

**Comment by LazeMSS** [comment]
@mac-za  you can just set the colors using the custom settings for colors

**Comment by LazeMSS** [comment]
Closing, but on the backlog - this is not 100% related - its hard to support all plugins colors etc in my themes.
