### ISSUE TITLE
http://192.168.1.31:5000/

### ISSUE THREAD

**Issue by Artifank** [LazeMSS/OctoPrint-UICustomizer#127]
## Description
**ENTER DESCRIPTION HERE
Describe your problem?
What is the problem?
Can you recreate it?
Did you try disabling plugins?
Did you remember to update the subject?**
<hr>

**Plugins installed**
- Active Filters Extended[active_filters_extended] v0.1.0
- Arc-Welder[arc_welder] v1.0.0+u.bb71e8f
- Autoscroll[autoscroll] v0.0.3
- BLTouch Plugin[BLTouch] v0.3.4
- Consolidate Temp Control[consolidate_temp_control] v0.1.8
- Cooldown Notification[CooldownNotification] v0.1.2
- Cost Estimation[costestimation] v3.2.0
- Cura Thumbnails[UltimakerFormatPackage] v0.2.2
- Detailed Progress[detailedprogress] v0.2.7
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.25.4
- Exclude Region[excluderegion] v0.3.0
- Filament Manager[filamentmanager] v1.7.2
- GcodeEditor[GcodeEditor] v0.2.12
- M73 Progress Plugin[m73progress] v0.2.1
- Marlin GCode Documentation[marlingcodedocumentation] v0.12.0
- Multi Colors[multi_colors] v1.0.17
- Multi Line Terminal[multilineterminal] v0.1.5
- OctoKlipper[klipper] v0.3.7
- OctoPrint-WiFiStatus[wifistatus] v1.5.5
- PrettyGCode[prettygcode] v1.2.4
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- Resource Monitor[resource_monitor] v0.3.2
- SetAndWait[setandwait] v0.0.1
- Tab Order[taborder] v0.5.12
- Tempsgraph Plugin[tempsgraph] v0.3.7
- Terminal Messaging[terminalmessaging] v0.1.0
- Themeify[themeify] v1.2.2
- Top Temp[toptemp] v0.0.1.3
- TouchUI[touchui] v0.3.17
- **UI Customizer[uicustomizer] v0.1.5.5**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: true
- filesFullHeight: false
- fixedFooter: false
- fixedHeader: false
- fluidLayout: true
- gcodeFullWidth: true
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- themeLocal: false

**Software versions**
- OctoPrint 1.5.3
- Python 3.7.3

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68

**Comment by LazeMSS** [comment]
What?

**Comment by LazeMSS** [comment]
Closing
