### ISSUE TITLE
Problems with printjobhistory - WAS:Plugin not behaving as intended

### ISSUE THREAD

**Issue by ZeekWorld** [LazeMSS/OctoPrint-UICustomizer#129]
Not sure if other plugins are taking over but since the last batch of plugins updates the ui got all messed up.
Tabs on top are set to only show icons, but they are showing text, there is a new widget in the center of the screen "General" Spool, Spool Vendor, etc I can't get rid of. Right side widget have shifted to the left column....

Here are the pictures..

![image](https://user-images.githubusercontent.com/16088952/114572540-d0307080-9c34-11eb-88eb-77b7962dac0e.png)

![image](https://user-images.githubusercontent.com/16088952/114572635-e5a59a80-9c34-11eb-95b6-19527af4c2ee.png)

![image](https://user-images.githubusercontent.com/16088952/114572693-f35b2000-9c34-11eb-865b-6ce09c279e43.png)

**Comment by ZeekWorld** [comment]
OctoPrint 1.6.0rc1 Python 3.7.3 OctoPi 0.18.0

**Comment by LazeMSS** [comment]
Could this be related to https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/134

**Comment by ZeekWorld** [comment]
Thank you, I will disable the Print History plugin and see how it goes.

**Comment by yourbuddydinec** [comment]
Same thing was happening to me when I updated the plugins it said needed it. Turning off PrintJobHistory fixed it so seems to be a problem between the two.

**Comment by ZeekWorld** [comment]
Yep, disabling PrintJobHistory fixes the UI

**Comment by LazeMSS** [comment]
Closing should be fixed now: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.6
