### ISSUE TITLE
Spool Manager doesn't work correctly when UIC is installed.

### ISSUE THREAD

**Issue by rfield19** [LazeMSS/OctoPrint-UICustomizer#133]
## Description
Can't see spool manager main window when UI customizer is enabled.
Describe your problem?
As description, main page of spool manager (ie clicking through to view / edit a spool) is completely blank when ui customizer is enabled.  
Previous version of UIC had the same problem, but it was possible to get SM working by disabling 'mobile/responsive' option.  Even that no longer works in current (installed 14/4/21) UIC though.
Can you recreate it?
Yes, it's persistent
Did you try disabling plugins?
Only thing that fixes it is disabling UIC

<img width="978" alt="Screenshot 2021-04-14 at 16 03 38" src="https://user-images.githubusercontent.com/81954195/114733266-1b34ab80-9d3b-11eb-87d6-33995a501255.png">

**Plugins installed**
- Auto Terminal Input[AutoTerminalInput] v0.1.0
- Autoscroll[autoscroll] v0.0.3
- Backup Scheduler[backupscheduler] v0.0.5
- Bed Visualizer[bedlevelvisualizer] v1.0.1
- BetterHeaterTimeout[BetterHeaterTimeout] v1.3.0
- BLTouch Plugin[BLTouch] v0.3.4
- Cost Estimation[costestimation] v3.2.0
- Creality-2x-temperature-reporting-fix[ender3v2tempfix] v0.0.4
- Cura Thumbnails[UltimakerFormatPackage] v0.2.2
- Custom Control Editor[customControl] v0.2.2
- Dashboard[dashboard] v1.18.1
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.26.0
- Enclosure Plugin[enclosure] v4.13.1
- Exclude Region[excluderegion] v0.3.0
- Filament Manager[filamentmanager] v1.7.2
- Friendly Neighborhood Beeper[FriendlyBeeper] v0.4.1
- GCODE System Commands[gcodesystemcommands] v1.0.1
- Long-SD-list-paths[LongPathSDList] v1.1.0
- M73 Progress Plugin[m73progress] v0.2.1
- Marlin EEPROM Editor[eeprom_marlin] v3.0.2
- Marlin GCode Documentation[marlingcodedocumentation] v0.12.0
- Navbar Temperature Plugin[navbartemp] v0.14
- Octoslack[Octoslack] v2.1.0
- Preheat Button[preheat] v0.7.2
- PrettyGCode[prettygcode] v1.2.4
- Printer Stats[stats] v3.1.2
- PrintJobHistory[PrintJobHistory] v1.12.dev1
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- PrusaSlicer Thumbnails[prusaslicerthumbnails] v0.1.4
- PSU Control[psucontrol] v0.1.11
- Resource Monitor[resource_monitor] v0.3.3
- Simple Emergency Stop[simpleemergencystop] v1.0.4
- Simple Filament Change Buttons[simple_filament_change_buttons] v1.1
- SpoolManager Plugin[SpoolManager] v1.3.3
- System Command Editor[systemcommandeditor] v0.3.4
- TouchUI[touchui] v0.3.17
- Ttprintercalibration Plugin[TTPrinterCalibration] v0.1.0
- **UI Customizer[uicustomizer] v0.1.5.6**
- Z Probe Offset[z_probe_offset] v0.5

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: false
- compressTempControls: false
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: true
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: false
- navbarplugintempfix: false
- responsiveMode: true
- themeLocal: true

**Software versions**
- OctoPrint 1.5.3
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15

**Comment by LazeMSS** [comment]
I can't recreate it on my Chrome or Firefox. There are some problems in can see in their issue list - the amount of dialogs etc put into the modal is hard to handle on responsive designs etc.

I wish I had the time to help with a redesign of the UI for the spool manager - the editor could really use a full screen dialog overlay instead of the modal stuff.

Closing because I can't fix it at the moment - sorry.
