### ISSUE TITLE
[Bug] - Closing UIC resets Appearance > Color settings

### ISSUE THREAD

**Issue by KenLucke** [LazeMSS/OctoPrint-UICustomizer#135]
Any time I preview or change themes, I have to go back and reset my Color settings in the Appearance tab, as they are reset to default.

Edit: Oops, it's not the changing themes that does it, it's just clicking Saved or Close leaving UIC.

Watch the Favicon in the upper left change after I close out UIC.
https://user-images.githubusercontent.com/57936294/114744344-71392d00-9d02-11eb-91c7-583e8100178b.mp4

**Comment by LazeMSS** [comment]
Yes this is kinda a problem because I had people sending me bug reports of "broken themes" which was really just people forgetting to turn off the colors in aperance. 

I agree it should not turn off the colors for the favicons - I will look into it.

**Comment by LazeMSS** [comment]
Actually I came up with a better idea - stay tuned ;)

**Comment by LazeMSS** [comment]
Fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.7

Please reopen/comment if not working as expected.
