### ISSUE TITLE
[Bug] Preheat Button does not change

### ISSUE THREAD

**Issue by KenLucke** [LazeMSS/OctoPrint-UICustomizer#136]
Not sure it this belongs here, or in the Preheat Button thread, but the behavior of the Preheat Button is failing.  It used to, when clicked, start the preheat and change its name to "Cool" (toggles "Preheat"/"Cool") with a cooling icon.  Now the icon changes, but the name of the button does not change from "Preheat" to "Cool."  

Preheating still starts, and stops when clicked again, but the button does not reflect the [opposite] state to toggle to.

https://user-images.githubusercontent.com/57936294/114752405-17893080-9d0b-11eb-820e-7c92bdeef04e.mp4

@jneilliii - see what happens when you make me start using a new plugin???  :) :) :)

**Comment by LazeMSS** [comment]
Made a PR to have this "fixed" in the preheat plugin:
https://github.com/marian42/octoprint-preheat/pull/53
