### ISSUE TITLE
Jittering Web UI

### ISSUE THREAD

**Issue by mon5termatt** [LazeMSS/OctoPrint-UICustomizer#138]
[the Webui is freaking out](https://cdn.mon5termatt.club/files/images/issue_OPUI.mp4), it looks like it is trying to hide the Scrollbar but isnt able to

not sure how to resolve this and the log isnt really helping on this one

**Comment by LazeMSS** [comment]
Does this only happen when running UI Customizer?

**Comment by LazeMSS** [comment]
Have you tried disabling the dashboard plugin?

**Comment by mon5termatt** [comment]
I will try later. Sorry for the late reply. I've been printing a time sensitive project and will work on it when I don't have a time limit. 

Zooming to 90% solves btw.

**Comment by LazeMSS** [comment]
@mon5termatt any news?

**Comment by mon5termatt** [comment]
I cannot get the issue to reoccur at this time
