### ISSUE TITLE
Larger main tab icons

### ISSUE THREAD

**Issue by AvanOsch** [LazeMSS/OctoPrint-UICustomizer#139]
Feature request:
It would be nice to be able to adjust the main tab icon size.
Simply adding the icon-style "fa-2x" (or "fa-3x" etc) changes the icon sizes.

I currently use the "Advanced --> Custom CSS" option to change the icon size:
`#tabs li>a {
    font-size: 2em;
}
`
Which also works fine, but an option to change it would be nice.
![example](https://user-images.githubusercontent.com/81688/114862230-8ee3c080-9dee-11eb-9f8d-6f33fb987c7c.jpg)

**Comment by LazeMSS** [comment]
Added in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.7

Please reopen/comment if not working as expected.
