### ISSUE TITLE
Doesn't work with multicam

### ISSUE THREAD

**Issue by gonzonia** [LazeMSS/OctoPrint-UICustomizer#14]
If I use the UI-Customizer I can no longer use the multi-cam plugin. The buttons for changing cams aren't available.

**Comment by LazeMSS** [comment]
I cant find a plugin named "multi-cam" - so please provide a link.

**Comment by gonzonia** [comment]
https://plugins.octoprint.org/plugins/multicam/

https://github.com/mikedmor/OctoPrint_MultiCam

**Comment by LazeMSS** [comment]
There is no buttons missing in my current version - I will release it later today

**Comment by LazeMSS** [comment]
Should be now fixed - please update and test :)

**Comment by gonzonia** [comment]
I see the button is back and I can change between cameras on the Control tab. Any chance to add the multi camera support into the new "Webcam" area?
