### ISSUE TITLE
[Bug] "Hide Main Webcam" does not work

### ISSUE THREAD

**Issue by KenLucke** [LazeMSS/OctoPrint-UICustomizer#141]
Enabling the "Hide Main Webcam" option does not hide the webcam - I still get it on all tabs (which appears to slow things down a bit, the camera feed gets stuttery).  

I use Dashboard, because I like the diagnostic information it displays, and I like having the webcam only on the Dashboard tab.   I tried turning all the others off with this option, and they persist, even after a restart.  I tried disabling Dashboard to see if it was somehow causing the option to be ignored, but nothing changed.    I also usually run a webcam feed only, in another web browser tab, if I want to really see what's happening larger size, and more smoothly.

It'd be nice to have the choice to enable or disable the webcam from each tab, too... I don't need a webcam showing all the time I'm doing everything, such as working in the Bed Visualizer or File Manager tabs .... or make a mini version (such as the mini version of the gcode viewer) that can be enabled in the sidebar.

Sorry to be a pain :)  I've beta tested stuff since the first Apple (not even Apple II) days in the 80s, and I'm always pushing the envelope :)

**Comment by LazeMSS** [comment]
No need to excuse. I love feedback.

**Comment by KenLucke** [comment]
> No need to excuse. I love feedback.

Don't encourage me :)

**Comment by LazeMSS** [comment]
Please split issues and feature request.
Regarding the Hide main webcam not working - I'm not sure what you mean. 

"Hide main webcam" hides the webcam from the Control tab.
There is a mini webcam similar to the gcode as you say  - so if you are talking about the webcam as a widget (right hand side af default) then just go the "Layout" tab inside UI Customizer and click the eye (hidden when there is a slash over it)

![image](https://user-images.githubusercontent.com/69049371/114983096-7deb8b80-9e90-11eb-8e29-196ce2dffb53.png)


![image](https://user-images.githubusercontent.com/69049371/114983183-952a7900-9e90-11eb-8cd3-f5ddd4a35a8f.png)

**Comment by LazeMSS** [comment]
@KenLucke ?

**Comment by KenLucke** [comment]
Yes?

**Comment by LazeMSS** [comment]
Can you try and explain a bit more - im not sure what the problem is?

**Comment by KenLucke** [comment]
> "Hide main webcam" hides the webcam from the Control tab and nothing else

This explains a lot.  I had the webcam set to the center panel, and it was shoing the Dashboard webcam PLUS the UIC webcam, both on the dashboard page. I was trying to turn the UIC one off, as it was not needed...the Dashboard version, plus my separate tab full window versuion for close inspection.  Moving the camera off to the sidebar and turning off the eye solved my problem.

**Comment by LazeMSS** [comment]
Okay I was reading it again and again and I couldn't make sense of it :)

I will rename that option :)

Okay to close?

**Comment by KenLucke** [comment]
> Okay to close?

Fine by me.
