### ISSUE TITLE
Text in white area almost unreadable 

### ISSUE THREAD

**Issue by ipa64** [LazeMSS/OctoPrint-UICustomizer#150]
Beautiful but text in input field with white background are almost unreadable 
Example terminal input field
How to change that ?
Thank you

**Comment by LazeMSS** [comment]
Which theme?

**Comment by ipa64** [comment]
Red night ( but I tried Dark green too, samething)

**Comment by LazeMSS** [comment]
I can't recreate - please post a screenshot and report a bit more info.
browser
plugins installed

**Comment by ipa64** [comment]
Safari 14.0.3
Here some print screen

[https://i84.servimg.com/u/f84/20/23/21/77/captur10.png](url)
[https://i84.servimg.com/u/f84/20/23/21/77/captur11.png](url)
[https://i84.servimg.com/u/f84/20/23/21/77/captur12.png](url)

Thank you

**Comment by ipa64** [comment]
I have just understand what was the problem !
I have Themify installed too and I thought it was disable but not !
So now all is ok, sorry to have bothered you
Thank you

**Comment by LazeMSS** [comment]
Okay thanks
