### ISSUE TITLE
Cosmetic

### ISSUE THREAD

**Issue by KenLucke** [LazeMSS/OctoPrint-UICustomizer#151]
When "Fixed Footer/Bottom Bar" is active, it cuts off the very bottom of the scrollable area.

![CR-10 v2 (Yellow) LAN  OctoPrint  - 16% 2021-05-01 12-15-19](https://user-images.githubusercontent.com/57936294/116792838-0153d200-aa78-11eb-99ba-8f448544bb36.jpg)
![CR-10 v2 (Blue) LAN  OctoPrint  - 6% 2021-05-01 12-17-25](https://user-images.githubusercontent.com/57936294/116792839-03b62c00-aa78-11eb-9e11-e80d86e1a7b3.jpg)
![image](https://user-images.githubusercontent.com/57936294/116792875-42e47d00-aa78-11eb-8389-02fbf35aaf67.png)

**Comment by LazeMSS** [comment]
What screensize?

**Comment by LazeMSS** [comment]
Do you maybe have another plugin installed?

**Comment by KenLucke** [comment]
I've tried several different screen resolutions, and it happens on all of them.  And yes, I have many other plugins installed.

**Comment by LazeMSS** [comment]
> I've tried several different screen resolutions, and it happens on all of them. And yes, I have many other plugins installed.

Any plugins that might change the bottom bar etc?
And does it happen with all themes?

**Comment by LazeMSS** [comment]
Give me a guide on how to recreate it and I will fix it :)

**Comment by KenLucke** [comment]
> > I've tried several different screen resolutions, and it happens on all of them. And yes, I have many other plugins installed.
> 
> Any plugins that might change the bottom bar etc?
> And does it happen with all themes?

Nothing that affects that in my knowledge.  It happens with at least two of them, I have not checked the others.

I don't do anything special to recreate it.  Just enable the bottom bar in UIC, and find a tab or two that require scrolling to get all the way to the bottom, then scroll all the way down.

**Comment by KenLucke** [comment]
Yes, it happens with all themes, I just ran through them (all I can do at the moment, I have every printer running, so I can't enable/disable plugins or try anything that would require a restart of OP.

**Comment by LazeMSS** [comment]
Ohh a tab is causing this.... Will look

**Comment by KenLucke** [comment]
![image](https://user-images.githubusercontent.com/57936294/116827544-4f3b0980-ab4e-11eb-95ee-320cb1512efa.png)

**Comment by KenLucke** [comment]
![image](https://user-images.githubusercontent.com/57936294/116827672-27987100-ab4f-11eb-944a-b6e2f83f04e4.png)

**Comment by KenLucke** [comment]
Basically, I think all it needs is a CSS tweak to make the main window area [BottomBar height less] when the bottom bar is on than it is when it is off.

**Comment by LazeMSS** [comment]
Okay I will test in Firefox now - give me a day or two - kinda frantic at the moment

**Comment by KenLucke** [comment]
No worries, it's just cosmetic at the worst (of course, your entire plugin is cosmetic, but what the heck < grin > )

**Comment by LazeMSS** [comment]
@KenLucke spent good 30 min. on this one I can't recreate it - either some custom css or another plugin is messing with something - no matter what i try i can't recreate it. I would really like to fix it so maybe you could try and list your plugins.

**Comment by KenLucke** [comment]
[plugin_list.json.zip](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/6446642/plugin_list.json.zip)

**Comment by LazeMSS** [comment]
@KenLucke  I still haven't figured out whats causing this...

I haven't tried all the plugins listed but I noticed a scroll to the "top arrow" on you screenshots - how did you get that? I'm missing that and that might be causing it.

**Comment by KenLucke** [comment]
That is from the Floating Navbar plugin.

**Comment by LazeMSS** [comment]
I can't recreate it - I thought it might be due to all the custom buttons below the terminal but doesn't seem to be the case.

1. Does it happen when using the default theme?
2. What is the pixel height of the footer when fixed is on: `$('.footer.navbar.navbar-fixed-bottom').height();`

**Comment by LazeMSS** [comment]
@KenLucke any news?

**Comment by LazeMSS** [comment]
@KenLucke  ping?

**Comment by LazeMSS** [comment]
Closing - haven't heard from @KenLucke  in 19 days - can't recreate :/
