### ISSUE TITLE
Height of "body.UICResponsiveMode #settings_dialog_content" is not set

### ISSUE THREAD

**Issue by thelastWallE** [LazeMSS/OctoPrint-UICustomizer#155]
I would like to start a discussion on this css rule:
```
body.UICResponsiveMode #settings_dialog_content {
	height: calc(100% - 40px);
}
```
This is for the height of the settings tabs after substarcting the navpills on respmosive mode.
### **Before:**
![117968597-a5fecb00-b326-11eb-8aa8-889bd178a3e3](https://user-images.githubusercontent.com/12502210/118178251-062f6300-b434-11eb-8148-4acee47348fc.png)
overflow on the parent div->buttons etc don't stay on top.

### **after the css rule:**
![Screenshot 2021-05-13 213018](https://user-images.githubusercontent.com/12502210/118178332-2101d780-b434-11eb-80e5-c23553f5902c.png)
overflow only on deeper div if set correctly from the plugin. Buttons staying on top.
As for now i need to set the css rule outside of my plugin to get the desired result.

**Comment by LazeMSS** [comment]
Just to make sure - you wan't me to add:
```
body.UICResponsiveMode #settings_dialog_content {
	height: calc(100% - 40px);
}
```

?

**Comment by thelastWallE** [comment]
This probably needs more testing. I had looked at a few plugins tabs and it was not breaking anything.
If the navpills have constantly the same height(40px) there wouldn't be a problem i think.
But yes i think it should be added, because it would leave the navpills on the top as you scroll down.
As it is now the overflown content causes the #settings_dialog_content to expand beyond the parent divs height and this would cause a scrollbar on the parent div.

**Comment by thelastWallE** [comment]
The same with your own settings tab:
![Screenshot 2021-05-14 115101](https://user-images.githubusercontent.com/12502210/118253918-c9eb1980-b4aa-11eb-9af3-d6c5fc273c97.png)
![Screenshot 2021-05-14 115121](https://user-images.githubusercontent.com/12502210/118253914-c8b9ec80-b4aa-11eb-85c2-14044aa674fb.png)
Would be better to be able to switch the tabs anytime.

**Comment by thelastWallE** [comment]
Needs some css settings on the plugins css, too:
![Animation](https://user-images.githubusercontent.com/12502210/118257675-31a36380-b4af-11eb-8924-3266a9d12f7a.gif)

**Comment by LazeMSS** [comment]
I get what you want to achieve but there are no rules in the current settings ie that says settings need to be built using tabs like this. I spent many days testing the current settings to be able to handle the many different plugins.

**Comment by LazeMSS** [comment]
Closing - will not implement - its not part of the main way of the UI working.
