### ISSUE TITLE
Dropdown Menu Disappears Off Screen

### ISSUE THREAD

**Issue by ruralaccent** [LazeMSS/OctoPrint-UICustomizer#16]
Hi. Great plugin. I'm already using it on two instances, but I have an issue where the dropdown plugins menu in the settings window disappears offscreen and I have to reduce browser scale size to be able to access all of the drop down menu items. 

I run 4k monitors on all of my computers. Octoprint 1.5.1.

Can a scroll bar be added to the menu or similar, or another fix? Or if there's not an easy fix, perhaps just provide an option to turn off the condensed settings page and let the original 'stock' one show instead? 

With scale at 100%:

![Untitled2](https://user-images.githubusercontent.com/51720842/101279698-e4aeb900-37bb-11eb-8dfb-71fd3cf2b13d.png)

When scaled down:

![Untitled](https://user-images.githubusercontent.com/51720842/101279701-eaa49a00-37bb-11eb-9ef2-0bfceeaeba7b.png)

**Comment by LazeMSS** [comment]
have you tried the latest version? 0.1.0.5 - it should help with these issues

**Comment by LazeMSS** [comment]
Confirmed - it is a bug :)

**Comment by ruralaccent** [comment]
I was just about to say, it's 0.1.0.5 that I'm running. I know I can deselect the mobile responsive box, but I do prefer the new settings layout so would like to use it, if possible. Many thanks :)

**Comment by LazeMSS** [comment]
I have it fixed in the next release - comming soon :)

**Comment by ruralaccent** [comment]
Great. Thank you.

**Comment by LazeMSS** [comment]
Please test to confirm its fixed in the latest version 0.1.0.9

**Comment by LazeMSS** [comment]
@ruralaccent  fixed or not?

**Comment by ruralaccent** [comment]
Sorry. I've only just had a chance to update the plugin this morning. I'll let you know ASAP.

**Comment by ruralaccent** [comment]
The fix works on both of my OctoPrint systems and when view by three different computers. The only issue  is hat the final item in the dropdown, whilst visible and clickable, is partially cut off. 

![Capture](https://user-images.githubusercontent.com/51720842/101627744-b973d600-3a16-11eb-84a8-49a40002ca2b.PNG)

It's not a big issue and doesn't affect usability.

**Comment by LazeMSS** [comment]
Ahh I will fix that last part in next update. Will close for now.

**Comment by ruralaccent** [comment]
Many thanks for your work on this :)
