### ISSUE TITLE
Switching Webcam (with multicam) screen jumps

### ISSUE THREAD

**Issue by Sleeepy2** [LazeMSS/OctoPrint-UICustomizer#162]
When you use the Webcam drop down to switch camera's the screen scrolls up. Not really sure how to describe it, I am in Octoprint Discord if you need a better explanation. In the first picture you can see the top of the window, with the tabs etc. After you switch it scrolls down and you can't see the top of the tabs.

Before switch
![image](https://user-images.githubusercontent.com/1533684/124647542-15df8c80-de64-11eb-8ee8-3c1d2cae6e0d.png)

After switch
![image](https://user-images.githubusercontent.com/1533684/124647578-255ed580-de64-11eb-9b33-ee86575899be.png)

**Comment by LazeMSS** [comment]
Will take a look ASAP
