### ISSUE TITLE
UI-Customizer running on WebView?

### ISSUE THREAD

**Issue by Jyers** [LazeMSS/OctoPrint-UICustomizer#170]
I was wondering if there was any way to get UI Customizer to play nice with chromium webview? I have a very strange android tablet that is pretty much purpose built just to run webview... It can run a full browser, but it's not the best experience. 

Is there any setting I can configure on the browser side that might help compatibility? Or is this just something that will most likely never function due to the nature of this plugin?

**Comment by LazeMSS** [comment]
It should do that but i can't test - what's the problem?

**Comment by Jyers** [comment]
@LazeMSS It just doesn't use the theme whatsoever. It goes back to default octoprint. If there is any way I can help/test to get this working I would be happy to :)

**Comment by LazeMSS** [comment]
Maybe its related to the webview - is there any easy way to test t?

**Comment by Jyers** [comment]
The first few of [these](https://www.makeuseof.com/tag/lightweight-android-browsers/) all use webview, so you can take your pick

**Comment by LazeMSS** [comment]
Tried the via browser on my Samsung mobile.

Seems to working as expected. Maybe the webviewer on your tablet is not updated.
![Screenshot_20210819-105409_Via](https://user-images.githubusercontent.com/69049371/130039864-9e3064bd-007d-4d98-8006-5e08f4af71ea.png)

![Screenshot_20210819-105355_Via](https://user-images.githubusercontent.com/69049371/130039899-d3dc3e58-8566-4400-a61b-c908aa171f45.png)

**Comment by LazeMSS** [comment]
@Jyers ?

**Comment by Jyers** [comment]
Interesting, I'll try it when I get home today

**Comment by LazeMSS** [comment]
@Jyers great let me know - I know there are some devices that don't get the latest webview - but maybe it can be sideloaded: https://www.apkmirror.com/apk/google-inc/android-system-webview/

**Comment by LazeMSS** [comment]
@Jyers  any news?

**Comment by Jyers** [comment]
I also was able to get the proper UI on my android device, but even after updating webview on the tablet I have not had any luck getting the UI to show up properly. It definitely seems like it is an individual issue of some kind with my device. Unfortunately I'm getting ready for a move right now so I don't have time to do a bunch of troubleshooting. But when I have time to try and figure it out I will update this in case it could help others.

**Comment by LazeMSS** [comment]
Okay will close - you can reopen if you find anything new.
Good luck moving :)
