### ISSUE TITLE
[Feature Request] True full screen camera

### ISSUE THREAD

**Issue by ManuelMcLure** [LazeMSS/OctoPrint-UICustomizer#172]
It would be really nice if the zoomed/floating camera had an icon I could click to make it truly full screen. Currently to achieve this I have to install the FullScreen Webcam plugin and uncheck "Hide webcamera on Control tab" so I can use that plugin to achieve true full screen webcam.

**Comment by LazeMSS** [comment]
On the to-do

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.6.2
Please check and reopen if not fixed/working as expected.

**Comment by electronicm** [comment]
With a 4:3 webcam, the lower part is cut off in landscape.

![Screenshot_2021-08-22-15-31-09-076_com android chrome](https://user-images.githubusercontent.com/13643227/130357169-563d104e-1ed4-4d33-9b86-a441810615d4.jpg)
![Screenshot_2021-08-22-15-31-03-491_com android chrome](https://user-images.githubusercontent.com/13643227/130357187-f52ca30c-be80-42c4-a2ea-268e5fb0d128.jpg)

**Comment by LazeMSS** [comment]
What resoultion is the webcam?

**Comment by electronicm** [comment]
960 x 720

**Comment by LazeMSS** [comment]
Thanks I think I have it fixed - you can try and add this to your custom css under advanced:
```
#UICWebCamFull img,#UICWebCamFull video{
    max-height: 100vh;
    max-width: 100vw;
}
```

And let me know it that works :)

**Comment by electronicm** [comment]
> #UICWebCamFull img,#UICWebCamFull video{
>     max-height: 100vh;
>     max-width: 100vw;
> }

This solves the problem

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.6.6
Please check and reopen if not fixed/working as expected.
