### ISSUE TITLE
Broken SD card, trying to recover custom CSS

### ISSUE THREAD

**Issue by SamGurdus1** [LazeMSS/OctoPrint-UICustomizer#173]
Hi, my SD card that I keep octopi on seems to have been partially corrupted. (I think...) I had a slightly out-of-date backup that got me most of the way back, but it was before I installed this plugin. I spent several hours customizing the CSS for my octoprint interface using this plugin, so I'd really like to recover the code. 

I'm still able to copy over certain files one by one, so I'm hoping that someone can point me towards where the CSS that I wrote is stored. Is there a specific file where I can find my custom styles?

**Comment by LazeMSS** [comment]
In the configuration file for OctoPrint
