### ISSUE TITLE
[Feature Request] pause and cancel in the header

### ISSUE THREAD

**Issue by electronicm** [LazeMSS/OctoPrint-UICustomizer#175]
Can you establish an option to have both the Pause and Cancel buttons in the header?
Especially on the smartphone with a fixed header, you could react more quickly to problems and interrupt printing.

**Comment by LazeMSS** [comment]
Not sure what you mean - there is a dedicated plugin for this im sure.

**Comment by LazeMSS** [comment]
https://plugins.octoprint.org/plugins/simpleemergencystop/ ?
