### ISSUE TITLE
Broken Info popup layout (OctoPrint 1.7.0rc2Python 3.7.3OctoPi 0.18.0)

### ISSUE THREAD

**Issue by LMS0815** [LazeMSS/OctoPrint-UICustomizer#176]
The layout of the Information (bell) screen seems to be broken.

![image](https://user-images.githubusercontent.com/8235214/129191577-75cce735-8982-4e52-8984-b6d96c20613e.png)

Tool popup seems to normal.

![image](https://user-images.githubusercontent.com/8235214/129191701-bd3ae4e3-fddb-4f0b-8d27-05c5567e5cf1.png)

[octoprint-systeminfo-20210812124320.zip](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/6975184/octoprint-systeminfo-20210812124320.zip)

**Comment by LazeMSS** [comment]
Will check asap

**Comment by LazeMSS** [comment]
Ahh this sometimes happens due the new modal dialogs - I will try and see if I can make a fix together with the main octoprint

**Comment by LazeMSS** [comment]
Ohh have you tried clearing your browser cache ?

**Comment by LMS0815** [comment]
Clearing the cache seems to fix the issue. (Although I see the small window which is resized on a slow system).

Thank you for the fast reply/solution,

**Comment by LMS0815** [comment]
Refresh only solves the issue on some systems (with 4:3 Monitor).
The issue seems to be related to the 16:9 Screen. 
If I move the window to my second 4:3 Monitor, the window is resized to the desired Size.
Moving it back keeps the size. After reloading same issue.

Same wit Edge and Chrome...

**Comment by LazeMSS** [comment]
This is not related to the UI Customizer plugin - it still happens if I disable it.
