### ISSUE TITLE
[FR] Add theme name to html head or body class names

### ISSUE THREAD

**Issue by jneilliii** [LazeMSS/OctoPrint-UICustomizer#180]
Please correct me if this exists already, but it would be great if the active theme name was added to the html or body class name list so that other plugins could adjust their css accordingly.

**Comment by LazeMSS** [comment]
Added in the next release

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.6.2
Please check and reopen if not fixed/working as expected.
