### ISSUE TITLE
Border around full screen Web Cam

### ISSUE THREAD

**Issue by ManuelMcLure** [LazeMSS/OctoPrint-UICustomizer#182]
Web cam shows with a border when full screen. The following in Advanced removes the border:
```
#UICWebCamFull {
   border: 0;
   border-radius: 0;
   padding: 0;
}
```

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.6.3
Please check and reopen if not fixed/working as expected.
