### ISSUE TITLE
Clicking on "release notes" in the "Themes have updated" popup brings up notes in same browser tab

### ISSUE THREAD

**Issue by ManuelMcLure** [LazeMSS/OctoPrint-UICustomizer#186]
If you click on the "release notes" link in the "Themes have updated" popup, the release notes come up in the same window and replace the OctoPrint instance. This is different from the release notes from OctoPrint's own Plugin Manager which automatically bring up another tab.

**Comment by LazeMSS** [comment]
Fixed in development - also include release notes in the popup.

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.6.6
Please check and reopen if not fixed/working as expected.
