### ISSUE TITLE
Main tab setting issue

### ISSUE THREAD

**Issue by Guilouz** [LazeMSS/OctoPrint-UICustomizer#19]
The new setting for customize main tab doesn't show all tabs, it's only show default tab, not others from plugins

With UICustomizer :

<img width="1017" alt="Capture d’écran 2020-12-08 à 19 08 29" src="https://user-images.githubusercontent.com/12702322/101523433-e37eb700-3988-11eb-8803-178a581db0e1.png">

With Tab Order plugin : 

<img width="971" alt="Capture d’écran 2020-12-08 à 19 09 17" src="https://user-images.githubusercontent.com/12702322/101523467-eda0b580-3988-11eb-833c-c524d2a9069e.png">

And is it possible to add setting to choose color of favicon like in Tab Order ?

<img width="635" alt="Capture d’écran 2020-12-08 à 19 12 45" src="https://user-images.githubusercontent.com/12702322/101523830-6869d080-3989-11eb-889b-6808561e02ca.png">

<img width="654" alt="Capture d’écran 2020-12-08 à 19 12 55" src="https://user-images.githubusercontent.com/12702322/101523837-6acc2a80-3989-11eb-86a0-67de244e8b81.png">

**Comment by knopancakes** [comment]
Seeing this affect the Octolapse plugin as well.
Octolapse used to be the left-most tab, now it is the right-most. There does not appear to be a way to move it or change the icon like the other main tabs.
![image](https://user-images.githubusercontent.com/16746364/101532523-af909b00-3962-11eb-96bb-de703a0ae248.png)

**Comment by LazeMSS** [comment]
Dohhh - I will fix it as soon as possible.

**Comment by LazeMSS** [comment]
Please test if fixed in latest release :)

@Guilouz i also added color picker and some more stuff

**Comment by Guilouz** [comment]
> Please test if fixed in latest release :)
> 
> @Guilouz i also added color picker and some more stuff

All plugins tabs now appears but color picker doesn't work, it can be changed but there no effect on the main tab.

**Comment by LazeMSS** [comment]
Ahh - btw. should the labels also be colored or only the icons?

**Comment by Guilouz** [comment]
> Ahh - btw. should the labels also be colored or only the icons?

Only icons.

**Comment by LazeMSS** [comment]
Please test with latest

**Comment by Guilouz** [comment]
> Please test with latest - is it fixed?

yes it's working now.

**Comment by LazeMSS** [comment]
Thanks
