### ISSUE TITLE
Updated to 0.1.6.8 Chrome nor Edge will not show multiple columns

### ISSUE THREAD

**Issue by bwerst** [LazeMSS/OctoPrint-UICustomizer#193]
Updated from 0.1.6.7 to 0.1.6.8 and I lost the three column layout.  I've tried multiple options in the plugin, but not sure where to go next. 

![image](https://user-images.githubusercontent.com/10964207/132430699-1a36ec1d-3eab-4629-b334-50424fbeed36.png)

![image](https://user-images.githubusercontent.com/10964207/132430823-fe35e5f6-2d8b-4868-8346-1c64c69c8950.png)

**Comment by longwa** [comment]
Same issue, Chrome on Mac OS. No columns.

**Comment by longwa** [comment]
Looking at the changes in this patch release, I'm surprised this wasn't saved for a larger release. These are definitely some non-trivial changes to the layout to make in a patch release. I feel like changes like this should've been targeted at a 0.1.7.x type branch at least with a bit of beta testing to boot.

https://github.com/LazeMSS/OctoPrint-UICustomizer/compare/0.1.6.7..0.1.6.8

**Comment by LazeMSS** [comment]
Not a major version - i normally just release when I have two new features/fixes.

**Comment by LazeMSS** [comment]
I have spent a lot of time testing this - the only majjor stuff is a rewrite of the plugin checks

**Comment by LazeMSS** [comment]
What version of octoprint are you running?

**Comment by LazeMSS** [comment]
BUG FOUND: Fix will be released ASAP - it you select a theme it will work until the new version is released.

**Comment by LazeMSS** [comment]
Fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.6.9

If not working please reopen/comment.

**Comment by bwerst** [comment]
0.1.6.9 solved the problem.  Thank you!  I really like having the multi columns and the compressed title bar with the key stats.

**Comment by LazeMSS** [comment]
Great - also look at toptemp if you haven't tried it
