### ISSUE TITLE
Save terminal size 

### ISSUE THREAD

**Issue by Merhim** [LazeMSS/OctoPrint-UICustomizer#198]
Hi Laze, great plugin!
Is it possible to save the terminal size configuration to make it persistent between browser reloads?

Thanks

**Comment by LazeMSS** [comment]
Should be possible :)

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.7.0
Please check and repopen/comment it not working as expected.
