### ISSUE TITLE
MultiCam DropDown is disappearing

### ISSUE THREAD

**Issue by Sleeepy2** [LazeMSS/OctoPrint-UICustomizer#199]
After the latest updated the MultiCam DropDown is gone when the screen first loads/refreshes.
Clicking on Settings then Save with no changes it shows up again.

**Comment by LazeMSS** [comment]
Yes it's fixed in the next release. Hopefully it will out this week.

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.7.0
Please check and repopen/comment it not working as expected.
