### ISSUE TITLE
Layout Bug

### ISSUE THREAD

**Issue by JFI611** [LazeMSS/OctoPrint-UICustomizer#2]
I changed my layout to have "State" as the first option in my layout/view and hit save. Once I saved everything was fine. However, once I reloaded Octoprint, the "State" always moves as the last option in the list/view. I tested this on all three columns with the same result.

**Comment by Guilouz** [comment]
Same here, change and save have no effect. I use last build.

**Comment by LazeMSS** [comment]
Fixed in 0.0.9.4: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.0.9.4

**Comment by LazeMSS** [comment]
> Same here, change and save have no effect. I use last build.
> 
> And plugins icons are centered, it must be on the right
> 
> <img alt="Capture d’écran 2020-11-30 à 21 34 02" width="2000" src="https://user-images.githubusercontent.com/12702322/100661580-f58ea300-3353-11eb-9bd4-1b833cafe1e3.png">

The icons are centered by design when running on big screens. Please report this a seperate issue if you want it customizable

**Comment by LazeMSS** [comment]
Next version will have this an option
