### ISSUE TITLE
Check and suggest installing SlicerThumbnail

### ISSUE THREAD

**Issue by dehart007** [LazeMSS/OctoPrint-UICustomizer#203]
Was curious what additional plug-in is required to get the STL preview in the file list as choosing that theme does not enable it.

Thanks

**Comment by LazeMSS** [comment]
https://plugins.octoprint.org/plugins/prusaslicerthumbnails/

You need to setup your slice to build them: https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails#configuration

**Comment by LazeMSS** [comment]
Maybe I should add that to the documentation or recommended plugins when installing my plugin.

**Comment by LazeMSS** [comment]
part of #217
