### ISSUE TITLE
OctoFlat Theme break UI Customizer - was: box background color is always white

### ISSUE THREAD

**Issue by tjmaxal** [LazeMSS/OctoPrint-UICustomizer#205]
## Description
**ENTER DESCRIPTION HERE
Describe your problem? the text backgrounds will not change from white for any theme
What is the problem? idk
Can you recreate it? yes 
Did you try disabling plugins? which one?
Did you remember to update the subject?**
<hr>

**Plugins installed**
- **UI Customizer[uicustomizer] v0.1.7.0**
- Access Anywhere - The Spaghetti Detective[thespaghettidetective] v1.8.2
- Terminal Messaging[terminalmessaging] v0.1.0
- SpoolManager Plugin[SpoolManager] v1.4.3
- OctoPod Plugin[octopod] v0.3.10
- OctoFlat Theme[octoflat] v0.2.0
- Dragon Order[dragon_order] v0.1.7
- Octolapse[octolapse] v0.4.1
- Marlin GCode Documentation[marlingcodedocumentation] v0.12.0
- Creality-2x-temperature-reporting-fix[ender3v2tempfix] v0.0.4
- Bed Visualizer[bedlevelvisualizer] v1.1.0
- Backup Scheduler[backupscheduler] v0.1.0

**UI Customizer settings**
- addWebCamZoom: false
- centerTopIcons: true
- compactMenu: false
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: false
- fixedHeader: false
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: false
- saveAccordions: true
- themeLocal: false

**Software versions**
- OctoPrint 1.6.1
- Python 3.7.3
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36

**Comment by LazeMSS** [comment]
Should now be included in the 0.1.8.0 release (https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.8.0) - please reopen if not working as expected.
