### ISSUE TITLE
Info tab breaks when using accordion save

### ISSUE THREAD

**Issue by CodeDev1809** [LazeMSS/OctoPrint-UICustomizer#207]
I noticed today that the Info tab will stop responding when closed. When using the setting "_Save accordion open/close state_" and leaving the Info minimized causes it to be come stuck in the closed state. I have not noticed this issue with any of the other tabs. I'm currently running Octoprint 1.7.0 on a raspberry pi 3B+ running Octopi 0.18.0.

**Comment by LazeMSS** [comment]
Thanks I will look ASAP

**Comment by LazeMSS** [comment]
The info tab is the same as state or what tab is your are reporting not working?

**Comment by CodeDev1809** [comment]
If I understand your question properly, the tab that was giving me problems was the Info Tab. I would become stuck in the collapsed position when using state saving. However, I just noticed it has completely disappeared for me (even though it is enabled and set to show), so it might be my install...

**Comment by CodeDev1809** [comment]
Yeah, here is a screenshot of the info tab stuck closed.
![Screenshot from 2021-10-18 18-28-48](https://user-images.githubusercontent.com/53279958/137815322-a9d1d7e1-1105-472a-8668-002e6113d001.png)
.

**Comment by LazeMSS** [comment]
Should now be included in the 0.1.8.0 release (https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.8.0) - please reopen if not working as expected.
