### ISSUE TITLE
Opt-out automatic updates

### ISSUE THREAD

**Issue by IzK666** [LazeMSS/OctoPrint-UICustomizer#210]
Why can't I opt-out checking for updates on startup on a regular way?
Can't you ask after installation whether I want or not update the plugin automatically?

**Comment by LazeMSS** [comment]
What tracking are you talking about?
New themes check?

**Comment by IzK666** [comment]
Yes.
It should be optional.

**Comment by LazeMSS** [comment]
It does not track anything. It basically just does a get on a public website that has no tracking enabled.

**Comment by IzK666** [comment]
Ok. But, can you make this checks optional? I don't see the point to do it automatically.
