### ISSUE TITLE
Cannot adjust terminal window to be able to see controls.

### ISSUE THREAD

**Issue by roontoon** [LazeMSS/OctoPrint-UICustomizer#214]
Cannot see controls without scrolling.

<img width="1357" alt="Screen Shot 2021-10-31 at 22 16 55" src="https://user-images.githubusercontent.com/874090/139612840-3cd4bdca-7f30-443d-9e60-d4ebbac91d12.png">

Cannot adjust window vertically. 
<img width="1367" alt="Screen Shot 2021-10-31 at 22 18 32" src="https://user-images.githubusercontent.com/874090/139612867-1f239b8a-fb38-43f0-b5ae-dda40ed7c2ef.png">

**Comment by LazeMSS** [comment]
What browser it - please use the submit a bug button in settings ;)

**Comment by roontoon** [comment]
Safari Will adjust down but not up.

**Comment by LazeMSS** [comment]
Closing this...
