### ISSUE TITLE
Setting all panels in a column to hidden makes the column 0px and panels are now lost.

### ISSUE THREAD

**Issue by DrieStone** [LazeMSS/OctoPrint-UICustomizer#222]
I hid all of my panels in the 3rd column, and after saving the column width became 0 and I can't make it bigger.

I can drag another panel into the column which allows me to change the column width, but some of my panels are now missing (don't show up at all).

Printer Notifications, Attention, and Octoklipper panel are no longer in my list.

![Screen Shot 2021-12-06 at 9 27 31 PM](https://user-images.githubusercontent.com/230261/144955240-3144e4e4-a394-4fe7-998e-d0ab23ac3881.png)

**Comment by LazeMSS** [comment]
Thanks for reporting - will look into it right away

**Comment by LazeMSS** [comment]
Until I have it fixes should probally uninstall the plugin and reinstall :)

**Comment by LazeMSS** [comment]
Fixed in 0.1.8.1
