### ISSUE TITLE
File Browser Frozen / Refresh Broken [Post 0.1.8.1 - Bugfixes]

### ISSUE THREAD

**Issue by brokenbrainguy** [LazeMSS/OctoPrint-UICustomizer#224]
After updating to the latest bug fix, 0.1.8.1, the file browser in the web UI is not reloading correctly. It shows the first item and then breaks, not reloading any new items. The first file from the list stays displayed, but the refresh function breaks.

**Comment by LazeMSS** [comment]
Will check ASAP

**Comment by brokenbrainguy** [comment]
> Will check ASAP

Let me know if there is anything I can provide. I'm going thru the theme to see if I can trace the bug.

**Comment by LazeMSS** [comment]
Try use the report a bug button - maybe a conflicting plugin etc.

**Comment by brokenbrainguy** [comment]
It seems to have been fixed with an update to the OctoPrint-SlicerEstimator plugin. Thanks

**Comment by LazeMSS** [comment]
Thanks ;) I could not reproduce ;)
