### ISSUE TITLE
"0.2.9.5 - Discoranged: Improved bed level visualizer" – ?????

### ISSUE THREAD

**Issue by codingcatgirl** [LazeMSS/OctoPrint-UICustomizer#226]
Today i got a "Themes Updated" notification with the title i put in this issue's title and the text below it being:

> Discoranged: Adjustments for the tables shown on Bed Visualizer tab

I have absolutely no idea what it is trying to tell me. Please explain.

**Comment by codingcatgirl** [comment]
A friend pointed out to me that there is a theme called "Discoranged". To me this read like "Discouraged" with a typo. So i guess now i understand, maybe it could be a good idea to still make it more clear that you're talking about a theme here.

**Comment by LazeMSS** [comment]
Thanks for pointing out. It was a bit speedy release
