### ISSUE TITLE
0.1.8.1 update - menu shows only 4 items

### ISSUE THREAD

**Issue by cicinovec** [LazeMSS/OctoPrint-UICustomizer#227]
After update to latest 0.1.8.1, the menu show only 4 items and the scroll bar has appeared, even on big screen when not necessary
![menu2](https://user-images.githubusercontent.com/33634908/149611971-f975b7c1-b3a2-4357-9c4c-3ca4fc25a4a9.png)
![menu1](https://user-images.githubusercontent.com/33634908/149611973-842b09c8-37c6-4536-aa58-c31bfa1d350c.png)

Tested in Chrome and Firefox

**Comment by Arsolix** [comment]
I have the same problem also.

**Comment by MrRexRuthless** [comment]
Same problem here two different installations.

**Comment by LazeMSS** [comment]
I'm fixing it today

**Comment by LazeMSS** [comment]
@Arsolix @cicinovec @MrRexRuthless could you please post a bug report with you settings or maybe a screenshot - i can not recreate it. Maybe just provide browser and os? But mostly what settings are being used.

**Comment by MrRexRuthless** [comment]
Please let me know if this is not what you need.  I'm accessing the PI/OctoPrint from Windows 10 using Edge.  It's happening on two different installations of OctoPrint.  Here are the logs as well.

[octoprint-logs.zip](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/7966692/octoprint-logs.zip)

Here is a screenshot as well

![image](https://user-images.githubusercontent.com/86332363/151713445-f0418f96-8309-48dc-a135-5211203c3357.png)

![image](https://user-images.githubusercontent.com/86332363/151713476-0184bb17-1ed6-4c3e-bf78-8de15cecec65.png)

This is one shot from each installation.

**Comment by LazeMSS** [comment]
Take a screenshot of the settings screen - and maybe use the "report a bug" button - that way i can see other plugins that might cause problems.

**Comment by MrRexRuthless** [comment]
![image](https://user-images.githubusercontent.com/86332363/151714528-d76c3a43-a373-4e59-869f-d56f5d7b04dd.png)
![image](https://user-images.githubusercontent.com/86332363/151714541-4da46610-f507-4269-9953-665a78c79eea.png)
![image](https://user-images.githubusercontent.com/86332363/151714551-b03c0db4-7a25-4e0c-90b7-959b18423366.png)
![image](https://user-images.githubusercontent.com/86332363/151714562-0334c5e7-9e97-4051-b487-4ea7021fa13a.png)

Done (issue 228)

**Comment by LazeMSS** [comment]
Thanks

**Comment by cicinovec** [comment]
Windows 10, Chrome and Firefox, both the same behavior.

Herebelow "report bug" export

**Plugins installed**
- Autologin Configuration[autologin_config] v0.2.0
- Autoscroll[autoscroll] v0.0.3
- Backup Scheduler[backupscheduler] v0.1.0
- BLTouch Plugin[BLTouch] v0.3.4
- Custom Control Editor[customControl] v0.2.2
- Detailed Progress[detailedprogress] v0.2.7
- DisplayZ[displayz] v0.2.0
- MultiCam[multicam] v0.2.8
- Navbar Temperature Plugin[navbartemp] v0.14
- OctoKlipper[klipper] v0.3.9.4
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- PSU Control[psucontrol] v1.0.6
- PSU Control - Tasmota[psucontrol_tasmota] v1.0.1
- SpoolManager Plugin[SpoolManager] v1.6.0
- **UI Customizer[uicustomizer] v0.1.8.1**


**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: false
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: true
- saveAccordions: false
- themeLocal: false


**Software versions**
- OctoPrint 1.7.3
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0

**Comment by LazeMSS** [comment]
its a bug in Spoolmanager plugin:
OllisGit/OctoPrint-SpoolManager#230
