### ISSUE TITLE
Using an iOS device resets column settings

### ISSUE THREAD

**Issue by jessemillar** [LazeMSS/OctoPrint-UICustomizer#229]
## Description
With UI Customizer installed, when I access OctoPrint through an iOS device (my iPhone or iPad) and change a setting (any setting, not necessarily a UI Customizer setting), often the column widths for UI Customizer automatically all get set to 1. This doesn't affect how OctoPrint displays on my iPhone (because it has a small screen), but my iPad and computer both immediately show the expected super skinny column widths. When the skinny columns are visible, if I go to the UI Customizer "Layout" settings, the correct column width will show (e.g. 4, 5, 3). If I save without changing any column width settings, nothing changes. If I change one of the column width settings, all three snap to 1 and then I can set the values back to the correct ones and save to fix the issue.

Can you recreate it?
- Yes. Pretty reliably.

Did you try disabling plugins?
- I have not tried disabling plugins yet.
<hr>

**Plugins installed**
- **UI Customizer[uicustomizer] v0.1.8.1**
- Print Scheduler[printscheduler] v0.0.4
- PrintJobHistory[PrintJobHistory] v1.16.0
- Preheat Button[preheat] v0.8.0
- Cura Thumbnails[UltimakerFormatPackage] v1.0.1
- TP-Link Smartplug[tplinksmartplug] v1.0.1
- Printer Stats[stats] v3.1.2
- Resource Monitor[resource_monitor] v0.3.6
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- PrettyGCode[prettygcode] v1.2.4
- OctoRant[octorant] v1.4.0
- M117PopUp[M117PopUp] v0.6.2
- Gcode Macros[gcode_macro] v1.1.1
- FileManager[filemanager] v0.1.6
- Filament Manager[filamentmanager] v1.9.1
- Dashboard[dashboard] v1.19.8
- Custom Background[custombackground] v1.0.0
- Cost Estimation[costestimation] v3.4.0
- Autoscroll[autoscroll] v0.0.3
- Macro[macro] v0.3.2
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- Creality-2x-temperature-reporting-fix[ender3v2tempfix] v0.0.4
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- Bed Leveling Wizard[bedlevelingwizard] v0.2.4

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: false
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: false
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: false
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: true
- themeLocal: false

**Software versions**
- OctoPrint 1.7.3
- Python 3.7.3

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.76

**Comment by LazeMSS** [comment]
Does this also happen if you disable all other plugins except:
Bed Visualizer[bedlevelvisualizer] v1.1.1
Bed Leveling Wizard[bedlevelingwizard] v0.2.4
PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8

I have never seen this problem and can't recreate it

**Comment by LazeMSS** [comment]
@jessemillar ping?

**Comment by jessemillar** [comment]
I disabled all third party plugins except the following:

- UI Customizer[uicustomizer]
- PrintTimeGenius Plugin[PrintTimeGenius]
- Creality-2x-temperature-reporting-fix[ender3v2tempfix]
- Bed Leveling Wizard[bedlevelingwizard]

I was actually experiencing some other OctoPrint issues prior to disabling the plugins so I wiped my Raspberry Pi's manually-installed OctoPrint and instead used a vanilla OctoPi image. I still experience the column size issue.

After making the changes above and testing for the size issue, I also tried disabling PrintTimeGenius and Bed Leveling Wizard. The issue actually went away at that point. I reenabled Bed Leveling Wizard and still didn't have the issue. After turning PrintTimeGenius back on, the issue returned.

The kicker is that I then reenabled all plugins except PrintTimeGenius and the issue still happened so maybe there's multiple plugins causing the issue? How can I assist in debugging?

For more info, I'm using Safari as my browser on my iOS devices. I have iOS 15.1 on my iPhone Xs and iOS 14.8.1 on my iPad Pro (12.9-inch) (3rd generation). I'm using 4, 5, 3 as my column widths.

**Comment by LazeMSS** [comment]
I really can't recreate it - tried on all 3 ipads and 2 iphones in my household without any of the problems. The problem with IOS browser is it quite hard for me to debug on. Do you have the same problem if you use a web browser or chrome on the IOS devices?

**Comment by LazeMSS** [comment]
I recreated the bug now - now to fix it!

**Comment by LazeMSS** [comment]
There might be something with having the UI open on multiple devices - do you have that when testing. I really can't seem to recreate this in any reliable way.

**Comment by jessemillar** [comment]
Hmmm. Interestingly, when I pulled up OctoPrint on only my iPhone and followed the recreation procedure above, the issue didn't happen. When I closed OctoPrint on my iPhone and desktop computer and tried to recreate the issue using only my iPad, the issue happened. And now it's happening consistently again regardless of how many devices have the UI open simultaneously.

**Comment by jessemillar** [comment]
What is UI Customizer's concept of a session? How long after I close OctoPrint in a specific browser does it take for UI Customizer to forget about that connection/client? Maybe I just didn't wait long enough...?

**Comment by LazeMSS** [comment]
I have no idea what's causing it. I have tried everything and it just randomly happens on my iPad but I can't recreate it to a degree that I debug it. I have improved the error handling of it.

Maybe I will also make an error message when it happens. At the moment it's handled silently 🙄

**Comment by jessemillar** [comment]
Thank you so much for working so hard to reproduce. Sorry to add a weird bug to the backlog!

**Comment by LazeMSS** [comment]
> Thank you so much for working so hard to reproduce. Sorry to add a weird bug to the backlog!

Can you try with the latest release?

**Comment by jessemillar** [comment]
I've tested it a few times now. Each time I save I get the following pop-up (which I assume if your new error message). My column sizes don't change anymore!
![image](https://user-images.githubusercontent.com/4627837/154822962-23b1bb96-2f6a-4948-ad33-c91ce9a426e7.png)

**Comment by LazeMSS** [comment]
Thanks - I will remove the alert

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.8.9
if not then please reopen this issue.
