### ISSUE TITLE
Drop down elements of header icons are hidden.

### ISSUE THREAD

**Issue by StaticNoise64** [LazeMSS/OctoPrint-UICustomizer#23]
New install of Octoprint

OctoPrint 1.5.2
Python 3.7.3
OctoPi 0.17.0

Additional Plugins: 
OctoPrint-WiFiStatus (1.4.0)
UI Customizer (0.1.1.1)

I found an error with the WiFi-Status plugin installed.

Using Chrome to inspect the elements I found the style of UIHeaderIcons is set to "Overflow: hidden" this is interfering with the dropdown menu of the plugin.

**Comment by LazeMSS** [comment]
Thanks will fix ASAP

**Comment by ertraid** [comment]
Hi. I think I stumbled against the same bug... just adding here in case it helps you.
In my case I am using MQTTPubilsh plugin (https://plugins.octoprint.org/plugins/mqttpublish/) which also displays a dropdown from the header bar, and they seem to be hidden when combined with UI customizer. StickyPad plugin seems to work fine though..

Great work with your plugin by the way!
ET

**Comment by ertraid** [comment]
Also, I only noticed this issue in the last day or 2.. Cannot swear, but I think it was working fine before.
ET

**Comment by ManuelMcLure** [comment]
I'm the author of OctoPrint-WiFiStatus and this was reported to me as well. I discovered that disabling the "Improve mobile/responsive" option resolves this issue, in case that helps debug this.

**Comment by LazeMSS** [comment]
> I'm the author of OctoPrint-WiFiStatus and this was reported to me as well. I discovered that disabling the "Improve mobile/responsive" option resolves this issue, in case that helps debug this.

Its fixed in the release - btw. I can't fork your plugin but I made a bunch of changes to it to improve the UI - have a look at: https://github.com/LazeMSS/OctoPrint-WiFiStatus

**Comment by LazeMSS** [comment]
Please test if the latest version(https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.2) does not fix it.

**Comment by LazeMSS** [comment]
Reported as fixed in Wifi plugin issue - closing

**Comment by StaticNoise64** [comment]
Sorry didn't get around to testing until today. That fixed the issue, thank you! Loving the plugin, good work!

**Comment by ertraid** [comment]
Agreed… solved issue with MQTT Publish plugin as well. Thanks!
