### ISSUE TITLE
[FEATURE] filebrowser height

### ISSUE THREAD

**Issue by newhinton** [LazeMSS/OctoPrint-UICustomizer#233]
**Describe the bug/feature**
When using the filebrowser, it can get stuck in a very awkward position because it is a scroll-container in a column that scrolls itself.

**To Reproduce**
1. Make the File Browser longer than the page height
2. scroll
3. see that scrolling behaves strangely because of the mouse cursor position

Would it be possible to make the filebrowser a tab in the Main Tab-View and in that a fixed height? This would make it more easy to use on desktop. It should not improve or break the usability on mobile.

**Comment by LazeMSS** [comment]
I not 100% sure what you mean but the problem with scroll inside a div is a generic one and can't be easy solved its the same with the terminal etc.

No I won't make an option to move the file browser into the main tabs - i would recommend using https://plugins.octoprint.org/plugins/filemanager/
