### ISSUE TITLE
[BUG] Window width layout and window styles went nuts

### ISSUE THREAD

**Issue by elpeter25** [LazeMSS/OctoPrint-UICustomizer#242]
## Description
Since version 0.1.8.7 page layout become nuts and so the icons and styles. Page width seems to have scroll as UI Customizer adds some margins left and right. Also control icons for temperature and so on went bigger making the style of the temp controls weird.
Please see pics so you can find differences I tried to describe.

Describe your problem? Page styles issue
What is the problem? Page and icons size are wrong.
Can you recreate it? Yes. I have screenshots of "before" and "after" the upgrade, also have an export file of 0.1.8.1 that I've used to revert back to make it work again after downgrading to that version. Will also attach it.
Did you try disabling plugins? Yes tried to disable as many plugins as I thought could clash but none fix it. Only downgrading and importing previous settings worked.

<hr>

**Plugins installed**
- **UI Customizer[uicustomizer] v0.1.8.9**
- TouchUI[touchui] v0.3.18
- Top Temp[toptemp] v0.0.1.7
- Terminal Messaging[terminalmessaging] v0.1.0
- Slicer Thumbnails[prusaslicerthumbnails] v1.0.0
- Simple Filament Change Buttons[simple_filament_change_buttons] v1.1
- Print Scheduler[printscheduler] v0.0.4
- TimeToFilament Plugin[TimeToFilament] v1.2.1
- Simple Emergency Stop[simpleemergencystop] v1.0.5
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.8
- Navbar Temperature Plugin[navbartemp] v0.14
- InlineConfirm[inlineconfirm] v1.1.4
- HeaterTimeout[HeaterTimeout] v0.0.4
- GcodeEditor[GcodeEditor] v0.2.12
- Floating Navbar[floatingnavbar] v0.3.7
- DisplayProgress[displayprogress] v0.1.3
- Custom Control Editor[customControl] v0.2.2
- Cancel Objects[cancelobject] v0.4.7
- Auto Terminal Input[AutoTerminalInput] v0.1.0
- Autoscroll[autoscroll] v0.0.3
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- Consolidate Temp Control[consolidate_temp_control] v0.1.8
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- Backup Scheduler[backupscheduler] v0.1.0

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: true
- saveAccordions: false
- themeLocal: false

**Software versions**
- OctoPrint 1.7.3
- Python 3.6.9

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

![0 1 8 1_OK](https://user-images.githubusercontent.com/37652763/157867480-2b4cb83a-7e15-4e43-898e-532305885a8a.png)
![0 1 8 7-9_KO](https://user-images.githubusercontent.com/37652763/157867482-c79d966a-b6ee-4da4-bee1-7024789c6267.png)
[UICustomizerSettings.json.txt](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/8231827/UICustomizerSettings.json.txt)

**Comment by LazeMSS** [comment]
Strange is this still a problem?

**Comment by elpeter25** [comment]
> Strange is this still a problem?

Yep, I'm afraid so. I have to install version 1.8.1 to have a proper view, otherwise it seems like the centre column has a wide right margin... I noticed it also on terminal tab.
Yesterday I installed two fresh octoprint installations and restoring the backup I had installed the latest version of the plugin so to make it visible I had to uninstall and install manually version 1.8.1...

**Comment by LazeMSS** [comment]
Can you take a screenshot of the layout tab in UI customizer settings?

**Comment by elpeter25** [comment]
> Can you take a screenshot of the layout tab in UI customizer settings?
![2022-03-24 11_35_11-63% 13_11 (printing)](https://user-images.githubusercontent.com/37652763/159898084-65c15634-bf77-4940-b9c3-788d0e0f1742.png)

**Comment by LazeMSS** [comment]
Sorry for the slow response - does it happen with all themes?

**Comment by LazeMSS** [comment]
@elpeter25 ?

**Comment by elpeter25** [comment]
> @elpeter25 ?

Sorry. I'm back.
Yes I've tried also with other themes and also happens.
Also I just updated to 1.8.0 of OP and still happens. Here you go the screenshot with other theme on latest OP.
![2022-05-19 16_46_18-0% - ()](https://user-images.githubusercontent.com/37652763/169325168-24cbaabe-8448-474e-9913-71c69ddd1a1e.png)

**Comment by LazeMSS** [comment]
Can you try disabling Consolidate Temp Contro

**Comment by LazeMSS** [comment]
Ohh and btw. no need to have both Navbar Temperature Plugin and TopTemp. And also the Floating Navbar is also included in UI Customizer - that might also be causing an conflict.

The size of the icons/buttons in the temperature can be controlled with the "Compact" option in UI Customizer but it might collide with the many other plugins you are running.

**Comment by elpeter25** [comment]
> Can you try disabling Consolidate Temp Control

That made the trick!
So it is a compatibility issue with that plugin then... but it didn't happen up to version 1.8.1

**Comment by elpeter25** [comment]
> Ohh and btw. no need to have both Navbar Temperature Plugin and TopTemp. And also the Floating Navbar is also included in UI Customizer - that might also be causing an conflict.
> 
> The size of the icons/buttons in the temperature can be controlled with the "Compact" option in UI Customizer but it might collide with the many other plugins you are running.
> 
> I would recommend you try turning off a plugin one at the time to figure out which one is causing the problems I have tried installing a couple of them but could not recreate it.

Thanks! I've disabled Navbar Temperature Plugin and Floating Navbar :)

**Comment by LazeMSS** [comment]
> > Can you try disabling Consolidate Temp Control
> 
> That made the trick! So it is a compatibility issue with that plugin then... but it didn't happen up to version 1.8.1

I wonder why that happend - I can't recreate :/

**Comment by elpeter25** [comment]
That's odd... for me disabling the consolidate temp control worked but I neeeeeed that plugin
Find attached the exported list of my installed plugins just in case it might help...
Not attached as it doesn't allow me to upload json so I tweaked it to be readable here:

```
"key": "uicustomizer", "name": "UI Customizer", "url": "https://github.com/LazeMSS/OctoPrint-UICustomizer"
"key": "touchui", "name": "TouchUI", "url": "https://github.com/BillyBlaze/OctoPrint-TouchUI"
"key": "toptemp", "name": "Top Temp", "url": "https://github.com/LazeMSS/OctoPrint-TopTemp"
"key": "terminalmessaging", "name": "Terminal Messaging", "url": "https://github.com/jeffeb3/OctoPrint-TerminalMessaging"
"key": "prusaslicerthumbnails", "name": "Slicer Thumbnails", "url": "https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails"
"key": "simple_filament_change_buttons", "name": "Simple Filament Change Buttons", "url": "https://github.com/TheThief/Octoprint_Simple_Filament_Change_Buttons"
"key": "printscheduler", "name": "Print Scheduler", "url": "https://github.com/jneilliii/OctoPrint-PrintScheduler"
"key": "TimeToFilament", "name": "TimeToFilament Plugin", "url": "https://github.com/eyal0/OctoPrint-TimeToFilament"
"key": "simpleemergencystop", "name": "Simple Emergency Stop", "url": "https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop"
"key": "PrintTimeGenius", "name": "PrintTimeGenius Plugin", "url": "https://github.com/eyal0/OctoPrint-PrintTimeGenius"
"key": "inlineconfirm", "name": "InlineConfirm", "url": "https://github.com/j7126/OctoPrint-InlineConfirm"
"key": "HeaterTimeout", "name": "HeaterTimeout", "url": "https://github.com/Andy-ch/OctoPrint-HeaterTimeout"
"key": "GcodeEditor", "name": "GcodeEditor", "url": "https://github.com/ieatacid/OctoPrint-GcodeEditor"
"key": "displayprogress", "name": "DisplayProgress", "url": "https://github.com/OctoPrint/OctoPrint-DisplayProgress"
"key": "customControl", "name": "Custom Control Editor", "url": "https://github.com/Salandora/octoprint-customControl"
"key": "cancelobject", "name": "Cancel Objects", "url": "https://github.com/paukstelis/OctoPrint-Cancelobject"
"key": "DisplayLayerProgress", "name": "DisplayLayerProgress Plugin", "url": "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress"
"key": "consolidate_temp_control", "name": "Consolidate Temp Control", "url": "https://github.com/jneilliii/OctoPrint-ConsolidateTempControl"
"key": "bedlevelvisualizer", "name": "Bed Visualizer", "url": "https://github.com/jneilliii/OctoPrint-BedLevelVisualizer"
"key": "backupscheduler", "name": "Backup Scheduler", "url": "https://github.com/jneilliii/OctoPrint-BackupScheduler"
```

Thanks for your time!!

**Comment by elpeter25** [comment]
IDK if this can be of any help...
![2022-05-25 22_46_03-0% - ()](https://user-images.githubusercontent.com/37652763/170364292-c5b3886b-da20-42b6-9970-a8e1c46d6c40.png)
![2022-05-25 22_46_25-0% - ()](https://user-images.githubusercontent.com/37652763/170364296-751d6998-df6c-4da8-b22c-50abd925f344.png)
![2022-05-25 22_45_47-0% - ()](https://user-images.githubusercontent.com/37652763/170364297-65eed79e-0028-40fc-83a6-77b536e5ecd8.png)

**Comment by elpeter25** [comment]
FYI I think I found something... In the "Consolidate Temp Control" plugin I have it set to "horizontal view" in settings.
![2022-05-30 09_39_29-Clipboard](https://user-images.githubusercontent.com/37652763/170941986-83b612df-0d63-49dc-8107-1aa3fd8e4b66.png)

If I change it to vertical there's no issue:
![2022-05-30 09_35_49-100% - (operational)](https://user-images.githubusercontent.com/37652763/170941814-99b8c5d3-0abc-49ff-b486-ddff0f2e98ea.png)

**Comment by LazeMSS** [comment]
@elpeter25  sorry for the long delay - I just tested - i now have the same problem but as soon as there is data in the terminal it is fixed.
I noticed in all you screenshots there is no data in the terminal. Can you test with data/connect to printer - does the terminal expand

**Comment by LazeMSS** [comment]
Found the bug and working with @jneilliii  to fix it :)

**Comment by elpeter25** [comment]
> Found the bug and working with @jneilliii to fix it :)

Awesome!! Thanks so so much for your work!! :)

**Comment by jneilliii** [comment]
Two options here. Either use my other Consolidated Tabs plugin or I just patched and TempControl you can install by copying/pasting the URL into Plugin Manager > Get More > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-ConsolidateTempControl/archive/refs/heads/bugfix/uicustomizer.zip
```

![image](https://user-images.githubusercontent.com/5249455/174296349-0db94dbe-317e-45af-adfb-28c01b0a79da.png)

**Comment by LazeMSS** [comment]
Closing for now

**Comment by jneilliii** [comment]
actually went ahead and created 0.1.9 release of Consolidated Temp Control plugin just now....

**Comment by elpeter25** [comment]
> Two options here. Either use my other Consolidated Tabs plugin or I just patched TempControl you can install by copying/pasting the URL into Plugin Manager > Get More > ...from URL and click Install.
> 
> ```
> https://github.com/jneilliii/OctoPrint-ConsolidateTempControl/archive/refs/heads/bugfix/uicustomizer.zip
> ```
> 
> ![image](https://user-images.githubusercontent.com/5249455/174296349-0db94dbe-317e-45af-adfb-28c01b0a79da.png)

Hi,

Sorry to trouble you this much but I cannot make it work... I tried installing version you sent above and latest 0.1.9 version from github (as it says been modified just few minutes ago)
Been strugeling with that trying to make it work, unisntalling, cleaning up data, reinstalling octoprint, trying another instance of octoprint, etc none of that make it work for me :(

How could we debug this? Maybe an Anydesk session will help?

Thanks for your time!!

**Comment by jneilliii** [comment]
What are your main settings?

![image](https://user-images.githubusercontent.com/5249455/174321612-3eb1a6dd-f1d2-4b04-b224-826b83573ba3.png)

**Comment by elpeter25** [comment]
One more test. I disabled every plugin but UI customizer + consolidate and tried another theme just in case:

![2022-06-17 16_46_23-Yang  OctoPrint  — Mozilla Firefox](https://user-images.githubusercontent.com/37652763/174321787-699bb873-4e5c-4ac5-ae46-d7d463e0b635.png)

**Comment by elpeter25** [comment]
> What are your main settings?
> 
> ![image](https://user-images.githubusercontent.com/5249455/174321612-3eb1a6dd-f1d2-4b04-b224-826b83573ba3.png)

![2022-06-17 16_48_23-Yang  OctoPrint  — Mozilla Firefox](https://user-images.githubusercontent.com/37652763/174321912-81277c75-1f7c-48af-95a0-0a64aaa5a4af.png)

**Comment by jneilliii** [comment]
That's strange, you have compress temp controls turned on, but they're not compressing. 

![image](https://user-images.githubusercontent.com/5249455/174324206-3393f290-36c8-4921-92b1-42439f05df03.png)

do you have anything added in UI Customizer's Advanced CSS section?

**Comment by jneilliii** [comment]
noticed your layout was 3 - 6 - 3, so changed mine to that and get the temp stuff cut off if not compressed, but with compressed option enabled it still shows ok.

![image](https://user-images.githubusercontent.com/5249455/174324911-9ad00b1d-50ae-46b2-8bc3-638959729788.png)

**Comment by elpeter25** [comment]
I tried with your settings with no result. Even tried 3 - 7 - 2, no luck either.
Just tested Firefox private window, same. Chrome, same :'(

**Comment by elpeter25** [comment]
Brand new installation with only UI Customizer and Consolodate Temp plugins installed. Same behavior:

![2022-06-17 17_22_43-OctoPrint](https://user-images.githubusercontent.com/37652763/174328643-176ec28b-8e63-40d4-afae-a71e995d2e3a.png)
![2022-06-17 17_22_38-OctoPrint](https://user-images.githubusercontent.com/37652763/174328645-d626f5be-3b3d-4024-a834-a9606b703965.png)

**Comment by elpeter25** [comment]
BTW window is 1920x1080 (have a 43" 4k display split in 4)

![2022-06-17 17_25_29-](https://user-images.githubusercontent.com/37652763/174329438-1190cea8-8975-4c90-82a4-3293fd30179f.png)
![2022-06-17 17_25_20-](https://user-images.githubusercontent.com/37652763/174329440-cc0a9de0-2030-4d4d-aa9e-a41df8912054.png)

**Comment by elpeter25** [comment]
Disabling following rule helps:

http://192.168.0.24:5009/plugin/uicustomizer/static/css/bootstrap-responsive.css
.row-fluid .span10 {
	width: 82.90598290598291%;
	*width: 82.8527914166212%;
}

![2022-06-17 22_51_11-Developer Tools — OctoPrint — http___192 168 0 24_5009__#tab_plugin_consolidate_](https://user-images.githubusercontent.com/37652763/174399527-a5eb0a02-3462-4616-8100-dd9c816fcdb1.png)

**Comment by elpeter25** [comment]
And setting this to 12.59 like left column (instead of 14.59) makes it look ok I think...

.row-fluid .span2 {
	width: 12.52991452991453%;
	*width: 14.476723040552828%;
}

![2022-06-17 22_54_52-Developer Tools — OctoPrint — http___192 168 0 24_5009__#tab_plugin_consolidate_](https://user-images.githubusercontent.com/37652763/174400030-f1dd0846-15c0-44bf-9a3b-282454cc265a.png)

**Comment by LazeMSS** [comment]
Will look more later.

**Comment by LazeMSS** [comment]
@elpeter25  could you please try and connect to a printer ?

**Comment by LazeMSS** [comment]
Something is really broken in your setup / the clean install did you restore settings for UICustomizer or something?
Could try uploading your settingsfile again - looking at your screenshots
https://user-images.githubusercontent.com/37652763/174400030-f1dd0846-15c0-44bf-9a3b-282454cc265a.png
https://user-images.githubusercontent.com/37652763/174399527-a5eb0a02-3462-4616-8100-dd9c816fcdb1.png

There is something setting a span10 on "tabable"
![image](https://user-images.githubusercontent.com/69049371/174456274-c1bf836c-9607-4f33-a536-8d7ca01ad9ed.png)

**Comment by jneilliii** [comment]
The changes to my plugin can be seen [here](https://github.com/jneilliii/OctoPrint-ConsolidateTempControl/commit/7ebdec69f24e6b44dff9e552c7c7bfd11146ad48), which is UI Customizer is detected the span10 is not added.

**Comment by jneilliii** [comment]
I would personally recommend switching from that Temp Control plugin to my Consolidated Tabs plugin. It should work for you way better with UI Customizer.

**Comment by LazeMSS** [comment]
Closing this - I spent 3 hours trying to recreate - please reopen and provide details on how to recreate again

**Comment by elpeter25** [comment]
Hi,
First I want to apologize for the late late response. Had some personal problem.

I "solved" it using your suggestions and I now use Consolidated Tabs plugin. Thanks so much for everything!!
