### ISSUE TITLE
USB cam[BUG]

### ISSUE THREAD

**Issue by wjflier** [LazeMSS/OctoPrint-UICustomizer#257]
**PLEASE USE THE "Report a bug" button found in settings**

That button will prefill everything and you don't have to do anything besides describe the problem.

**Describe the bug**
USB cam doesn't load in side panel

**To Reproduce**
1. What settings are you using in UICustomizer
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
webcam to load

**Screenshots**
![image](https://user-images.githubusercontent.com/8867508/174600488-8cd91205-f572-4339-8c2e-577ede7adf52.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win10
 - Browser [e.g. chrome, safari]opera

**Smartphone (please complete the following information):**

**Additional context**
using raspberry 4 with usb camera, shows up in control, but switching to pretty gcode, the cam doesn't load in Pretty gcode or, on the side panel.

**Comment by LazeMSS** [comment]
Does it work without UI Customizer

**Comment by wjflier** [comment]
Got it

**Comment by LazeMSS** [comment]
@wjflier can we close this?

**Comment by captainwasabi** [comment]
I am having this problem. It was working, then it stopped.  The camera shows up on the dashboard and in the controls panel, but not the side panel.
