### ISSUE TITLE
Erro on Firefox/Chrome console when close/save settings

### ISSUE THREAD

**Issue by SinisterRj** [LazeMSS/OctoPrint-UICustomizer#262]
## Description
I get this error everytime that I need to close or save the octoprint's settings when UI Customizer is active:

`Error calling onSettingsHidden on view model UICustomizerViewModel : Empty streamUrl. Cannot determine stream type.`

Can you recreate it?
Yes

Did you try disabling plugins?
Yes. The problem only happen with UI Costomizer.

<hr>

**Plugins installed**
- Safety Printer[SafetyPrinter] v0.1.0
- **UI Customizer[uicustomizer] v0.1.9.0**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: false
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: false
- themeLocal: false

**Software versions**
- OctoPrint 1.8.2
- Python 3.8.10

**Browser**
- Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.1 - please reopen if not working.
