### ISSUE TITLE
[FR] - Set Page Title

### ISSUE THREAD

**Issue by Tukamok** [LazeMSS/OctoPrint-UICustomizer#263]
## Description
I would like to be able to set/override the page title.

I have two printers and two instances of Octoprint running and it would be nice to be able to set the page title to show a unique identifier for each of them so I can differentiate at a glance between them.

**Plugins installed**
- Calibration Tools[CalibrationTools] v1.0.4
- Camera Settings[camerasettings] v0.4.0
- Dashboard[dashboard] v1.19.8
- Octolapse[octolapse] v0.4.1
- Persist Terminal Command History Plugin[persist_terminal_command_history] v0.2.0
- TpLinkHandler[TpLinkAutoShutdown] v1.3.0
- **UI Customizer[uicustomizer] v0.1.9.0**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: false
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: false
- themeLocal: false

**Software versions**
- OctoPrint 1.8.2
- Python 3.9.2

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

**Comment by LazeMSS** [comment]
This can be done by using standard settings, Octoprint -> Apperance 
![image](https://user-images.githubusercontent.com/69049371/191179611-823b55ad-c01f-40d2-bdd8-1a68dcae7b52.png)
