### ISSUE TITLE
[FR] Cancel Button Actions

### ISSUE THREAD

**Issue by SemperFi89** [LazeMSS/OctoPrint-UICustomizer#268]
I would like the ability to configure the actions that are taken when the user hits the cancel button in the State box.  Currently when you hit cancel it just stops right where it is and shuts off the heaters.  For me, I want it to move X to **0** and Y to (either **max** or a fixed number if you can't use a variable).

**Comment by LazeMSS** [comment]
Maybe take a look here:
https://plugins.octoprint.org/plugins/inlineconfirm/

**Comment by SemperFi89** [comment]
> Maybe take a look here: https://plugins.octoprint.org/plugins/inlineconfirm/

Per the description, it only will get rid of the confirmation box of the cancel.  I want to be able to send something like G0 X 0 Y 235 once the cancellation is confirmed to put the print head at the far left and move the bed completely out.  I don't care if there is a popup to confirm or if I have to double-click cancel.

**Comment by LazeMSS** [comment]
Sorry but is this not handled in OctoPrint Settings > Printer > GCODE Scripts > After print job is cancelled?

**Comment by SemperFi89** [comment]
It is, i found that later.  thanks for your help

Sent from Nine<http://www.9folders.com/>
________________________________
