### ISSUE TITLE
HLS Wyzecam Stream not showing up on dashboard but works within settings.

### ISSUE THREAD

**Issue by msrlrocket** [LazeMSS/OctoPrint-UICustomizer#269]
Hi, I have an HLS steam that I am trying to use for the webcam. This camera works when I have UICustomizer disabled and does not when its enabled. Upon opening Octoprint, It will show the controls for the printer jammed at the top with two little volume and expand buttons but no stream. I have seen that adding a new camera plugin that shows on the right-hand side will also show the camera.

**Comment by msrlrocket** [comment]
Discovered that if I click the small PIP button at the top since it looks like the CSS collapsed it will open in a small window with camera working.

**Comment by LazeMSS** [comment]
I will try and test ASAP

**Comment by LazeMSS** [comment]
This is expected to be fix in the upcoming 0.1.9.4 release combined with the OctoPrint 1.9.0rc3 and later versions.

**Comment by LazeMSS** [comment]
This should now be fixed when 1.9.0 is released - closing for now - wait for 1.9.0 release or try the RC3 version.
https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.4
