### ISSUE TITLE
[BUG] Top of expanded webcam view is behind fixed top navbar

### ISSUE THREAD

**Issue by holocronology** [LazeMSS/OctoPrint-UICustomizer#27]
[
 When expanding the webcam view to "full screen" the top of it is hidden behind the top fixed navbar. You can drag it down to get to the click point to close/minimize it. 
![image](https://user-images.githubusercontent.com/65265114/101989543-af481680-3c66-11eb-8f52-f964007c1a72.png)

]

**Plugins installed:**
- DisplayLayerProgress
- GcodeEditor
- PrintTimeGenius
- action_command_notification
- action_command_prompt
- announcements
- arc_welder
- backup
- bedlevelvisualizer
- consolidatedtabs
- discovery
- errortracking
- filamentmanager
- gcodeviewer
- marlingcodedocumentation
- pi_support
- pluginmanager
- simpleemergencystop
- softwareupdate
- tracking
- uicustomizer
- virtual_printer

**Software versions:**
- OctoPrint 1.5.2
- Python 2.7.16
- OctoPi 0.17.0

**Comment by LazeMSS** [comment]
@holocronology 
Please confirm its fixed in the latest release:
https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.3
... if so then feel free to close this - thanks.

**Comment by holocronology** [comment]
Bug appears to remain.

The top right corner, with the minimize click point, is outside the window. However, the expanded window is now on top of the fixed navbar. Previously, it was behind the fixed navbar.

![image](https://user-images.githubusercontent.com/65265114/102084416-bdb73f00-3dda-11eb-856f-1e43400dc3c0.png)

**Comment by LazeMSS** [comment]
What is the screen/browser size and webcam resoultion you are using?

**Comment by LazeMSS** [comment]
Btw. closing this bug - this is fixed - the size problem is also here - please report size etc. there
https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/26
