### ISSUE TITLE
Some colors in the Blue Moon theme are almost unreadable. 

### ISSUE THREAD

**Issue by rbrian** [LazeMSS/OctoPrint-UICustomizer#275]
For example, the icons in the Plugin Manager: 

![image](https://user-images.githubusercontent.com/151535/215360113-2fd9713e-98f0-4241-8da9-fffb121971fb.png)

There are others, this is just the one that was in front of me when I thought to report it.

**Comment by LazeMSS** [comment]
Will be fixed in themes later today
