### ISSUE TITLE
Unresponsive UI in Firefox

### ISSUE THREAD

**Issue by MrVenerabilis** [LazeMSS/OctoPrint-UICustomizer#283]
This plugin looks nice so far.

When the UI is opened in desktop Firefox, the webcam stream wont load and the UI becomes unresponsive.
When changing the tab, the whole tab crashes and a loading symbol is displayed.
The UI and the plugin are working perfect in an other browser or on mobile firefox.

I tried to disable all plugins, but still not working.

**Steps to reproduce the behavior:**
1. Install the plugin
2. changes settings or not, doesnt matter.
3. see unresponsive UI

**Desktop:**
 - OS: Windows 11
 - lastest firefox

**Comment by LazeMSS** [comment]
This is expected to be fix in the upcoming 0.1.9.4 release combined with the OctoPrint 1.9.0rc3 and later versions.

**Comment by LazeMSS** [comment]
This should now be fixed when 1.9.0 is released - closing for now - wait for 1.9.0 release or try the RC3 version.
https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.4

**Comment by MrVenerabilis** [comment]
Perfect, thank you very much! Will try it out soon
