### ISSUE TITLE
[BUG] Duplicate camera in side panel

### ISSUE THREAD

**Issue by dannybloe** [LazeMSS/OctoPrint-UICustomizer#287]
Howdee, 

Just installed the plugin and I noticed that the camera is duplicated in the side panel:

![image](https://user-images.githubusercontent.com/2369994/231403954-a59946b0-895f-4044-8351-4da86e0b745a.png)

Looks like there a two identical divs in the DOM.

Cheers,
Danny

**Comment by LazeMSS** [comment]
Would you care to upgrade to the rc of octoprint?

**Comment by dannybloe** [comment]
Mm.. weird. I didn't get notified about your replies even though I have all notification settings enabled.

Anyway.. ehm... I'd rather wait till the rc is final to be honest. Isn't that soon anyway?

**Comment by LazeMSS** [comment]
Strange i did not get the update either - yes i don't think it will be long before the final is out

**Comment by LazeMSS** [comment]
@dannybloe was this fixed at least? :)

**Comment by dannybloe** [comment]
Well, it's not working at all anymore. See https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/293

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.8

Please check and reopen if not working - thank you...
