### ISSUE TITLE
Font is now changed 

### ISSUE THREAD

**Issue by henrikkoch** [LazeMSS/OctoPrint-UICustomizer#288]
Font in the Dark Green theme so that it looks very condensed and hard to read on PC. On tablet it looks correct. Just realize it is the most of the themas that now have a problem. Not the Prusa Tribute and Cosmo seams to have the font issue

**Comment by LazeMSS** [comment]
What version are you running - could you provide a screenshot?

**Comment by LazeMSS** [comment]
And make sure you did not zoom in/out on you browser? :)

**Comment by LazeMSS** [comment]
No reply - closing
