### ISSUE TITLE
Webcam orientation and Gcode Viewer size

### ISSUE THREAD

**Issue by JanB97** [LazeMSS/OctoPrint-UICustomizer#29]
The Webcam on the side  does not care about the orientation settings in octoprint.
It is always the wrong orientation until I go in and disable and enable to flip the webcam again.
After I reload the webpage it is wrong again.

Also the GCode viewer doesn't scale if the center row is more than 4.

And I have a feature request for this otherwise great Plugin! (I don't know where to post this else)
Could you maybe make like a extra layout category to have buttons that execute own scripts or something like that?
All other options involve GCode which does freeze the print...

**Comment by LazeMSS** [comment]
What is the URL of your webcam? Is it HLS or normal?
Post a screenshot of you webcam settings and share what it should look when it works and when it doesn't work.

Everything works fine for me and everybody else testing - so I need more info.

**Comment by JanB97** [comment]
Its an IR Camera using the PI Webcam Interface.
The URL is: /webcam/?action=stream

This is how to should look: 
![image](https://user-images.githubusercontent.com/7881168/102023642-4d360100-3d8d-11eb-9014-0f0dfc37e109.png)

This is how it does look:
![image](https://user-images.githubusercontent.com/7881168/102023696-98501400-3d8d-11eb-8ef3-5cef758bb39e.png)

It seems like this only happens if the main cam is hidden.
It also doesn't seem to happen every time.

Settings:
![image](https://user-images.githubusercontent.com/7881168/102023735-c9c8df80-3d8d-11eb-98f2-04317e6febd4.png)


This is the Gcode Viewer:
![image](https://user-images.githubusercontent.com/7881168/102023752-efee7f80-3d8d-11eb-9fa6-f59842b93e2a.png)

**Comment by LazeMSS** [comment]
The gcode viewer is full width on my installation - it could be one of your plugins changing the way the canvas is done. I will look later on the other stuff.

**Comment by LazeMSS** [comment]
I have run my webcam the same way as yours for 4-5 hours now - no problems at my part - i can' reproduce

**Comment by LazeMSS** [comment]
@JanB97  try the latest version and see if it still happens. - thanks - if not then please close this issue

**Comment by JanB97** [comment]
Okay, you are right, it's the Plugin "Exclude Region" that causes the GCode Viewer behavior in connection with your Plugin.
And the Webcam Problem is caused with the Plugin Dashboard and your Plugin active.

As it is in connection with other Plugins it might not really be a Problem of your Plugin, but it is only happening if yours is active.
As I find your way better in usability, I will however deactivate those and keep yours active. 
Thanks :)

**Comment by LazeMSS** [comment]
I will look and see what causes it with these plugins
