### ISSUE TITLE
Issue with icons on the tab order panel:

### ISSUE THREAD

**Issue by JKinch** [LazeMSS/OctoPrint-UICustomizer#291]
Hi, while in settings i cant seem to search icons anymore while messing with TAB order/names/etc under the main tabs panel in settings. 

Get "Error searching… Error: 0 (error)". Very minor issue. Running on a a RPi3B and was installed all offline due to operating on a local only network. Since i cant find this issue elsewhere, i have a feeling the installation expects a internet connection that wasn't present. 

![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/44818309/68120168-5675-4918-8b80-a48bbaa68859)
[octoprint-logs.zip](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/11508436/octoprint-logs.zip)

[plugin_list.json.txt](https://github.com/LazeMSS/OctoPrint-UICustomizer/files/11508387/plugin_list.json.txt)

Any help would be appreciated, as currently i cant fit all tabs on screen in this 4:3 monitor. Browser is Google Chrome and Edge, both at latest versions, can pull version info if needed.

**Comment by LazeMSS** [comment]
Sorry i have been away. Will look later today

**Comment by LazeMSS** [comment]
Yes this bug is true - it uses the api from font awesome to search for icons. I won't fix it.

**Comment by JKinch** [comment]
Is there not a solution for users?

**Comment by LazeMSS** [comment]
I think you browser is blocking for the access - i will look a bit more

**Comment by jneilliii** [comment]
You could convert to a local-only search box couldn't you? That's how my Tab Order plugin does it using [this](https://github.com/jneilliii/OctoPrint-TabOrder/blob/master/octoprint_taborder/static/js/fontawesome-iconpicker.js).
