### ISSUE TITLE
Octoprint Browser Resolution

### ISSUE THREAD

**Issue by clarkiej** [LazeMSS/OctoPrint-UICustomizer#295]
This is not an issue but a query:
Is it possible to change the browser screen resaolution in UI-Customiser like you can in Themify with the .span8 and .container parameters : 

![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/81622030/1c7ce4f2-fa21-4c13-abd7-cc03b1f843ee)
 depending on teh screen resolution you are viewing with?

**Comment by LazeMSS** [comment]
Not sure what you want, but in the advanced section you can make custom CSS

**Comment by LazeMSS** [comment]
So yes you can basically just ad this in the advanced section of UI Customizer under custom css:
```
.span8{
width: 880px
}
.container{
width: 1200px
}
```
But I would not recommend it as it might break the responsiveness of the UI
