### ISSUE TITLE
Add possibility to choose position of plugins icons

### ISSUE THREAD

**Issue by Guilouz** [LazeMSS/OctoPrint-UICustomizer#3]
Plugins icons are centered, is it possible to add option choose position to align with others (to the right like original octoprint) ?

<img width="2557" alt="Capture d’écran 2020-11-30 à 21 34 02" src="https://user-images.githubusercontent.com/12702322/100661580-f58ea300-3353-11eb-9bd4-1b833cafe1e3.png">

**Comment by LazeMSS** [comment]
Will be in next release as an option:
https://github.com/LazeMSS/OctoPrint-UICustomizer/commit/d1e0171427de5b4183622c59ea8a23a9d32e541f
