### ISSUE TITLE
Enhancement request: Combining some of the main tabs

### ISSUE THREAD

**Issue by DrewBatchelor** [LazeMSS/OctoPrint-UICustomizer#30]
This plug in is brilliant, Thank you.
Just an idea for an enhancement request, It would be amazing if it could be possible to combine the main tabs.
For example the Temperature tab and the Dashboard tab. With the temperature tab on top and Dashboard tab below would fit on 1 screen for me.
Likewise Terminal and Klipper could be stacked into 1 tab as well. 
Kind Regards
Drew

**Comment by jneilliii** [comment]
You could technically use Consolidated Tabs plugin in conjunction with UI Customizer to achieve this.

![image](https://user-images.githubusercontent.com/5249455/102962140-25911800-44b4-11eb-9492-4fbb2ec3c675.png)

**Comment by Jack1337** [comment]
Really thank you for this plugin! its awesome!
it would be awesome when we could combine tabs like klipper and terminal, or Temperatur and Control.
Or maybe not combine them, just split the MainTabs and place one by one.
so i cloud place both among themselves.

Thank you!!

**Comment by LazeMSS** [comment]
> Really thank you for this plugin! its awesome!
> it would be awesome when we could combine tabs like klipper and terminal, or Temperatur and Control.
> Or maybe not combine them, just split the MainTabs and place one by one.
> so i cloud place both among themselves.
> 
> Thank you!!

As @jneilliii  pointed out he already has a plugin that does some of this

**Comment by jneilliii** [comment]
I'd also be happy to collaborate on making that plugin more compatible with UI Customizer.

**Comment by LazeMSS** [comment]
> I'd also be happy to collaborate on making that plugin more compatible with UI Customizer.

When back from holiday I will probally make some changes :)

**Comment by NovaViper** [comment]
Is there any progress on this? I'd be more than willing to test this out on my Octo instance

**Comment by jneilliii** [comment]
I've made some progress on my side. If you want to try it out, you can install by copying/pasting the URL below into plugin manager > get more > ...from URL. Sizing the panels seems way more stable now since implementing gridstack and @LazeMSS has helped with getting through an initial bug I was having with the implementation. I've had positive feedback so far with this version on its own and it is compatible with UI Customizer now.

```
https://github.com/jneilliii/OctoPrint-ConsolidatedTabs/archive/develop/gridstack.zip
```

**Comment by NovaViper** [comment]
@jneilliii Er.. is it suppose to show only the settings? Im only getting this and no option to modify it
![image](https://user-images.githubusercontent.com/7191115/109012082-36f2ce00-7677-11eb-9ed3-d2cee47a9927.png)
![image](https://user-images.githubusercontent.com/7191115/109012120-43772680-7677-11eb-9b7a-4de832f85dc3.png)

**Comment by jneilliii** [comment]
click the edit button (pencil icon) in the navbar...

**Comment by NovaViper** [comment]
Ah I see! Thanks, I got it together and it seems to be working fine with the control, temp and OctoKlipper tabs.

**Comment by David-Maisonave** [comment]
I didn't know there was a ConsolidatedTabs Plugin.  I just tried both together and they work great. It would be nice if the two plugins could be consolidated into one plugin.

Thank you both for these great plugins.

**Comment by LazeMSS** [comment]
Closing - handled by ConsolidatedTabs
