### ISSUE TITLE
Hide webcamera on Control tab - don't work

### ISSUE THREAD

**Issue by fly74** [LazeMSS/OctoPrint-UICustomizer#300]
Hi Devs,

the option "Hide webcamera on Control tab" don't hide the webcam on control tab. And with this behavior the webcam can't displayed on the overview page.

Environment is:
octoprint 1.9.1
Classic Webcamplugin disabled
Multicam Plugin 0.4.0

It would be nice to show multiple webcams at one time here :):

![Screenshot 2023-07-18 115415](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/38754941/1930656c-3a94-457f-a58f-c220986a0713)

**Comment by fly74** [comment]
Ah multiple cams at a time are already here https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/206 discussed.

**Comment by LazeMSS** [comment]
There is a problem with the webcam in the new release I trying to figure out the best way to fix it

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.8

Please check and reopen if not working - thank you...
