### ISSUE TITLE
Webcam disappears in Octoprint but works in browser window url

### ISSUE THREAD

**Issue by bdare088** [LazeMSS/OctoPrint-UICustomizer#301]
## Description
Webcam in Octoprint loses stream but  /webcam/?action=stream works fine in separate browser window

Describe your problem?
Upgraded to Octoprint 1.9x with new cameras stack recently and had webcam issues. Thought is was hardware and tried 2 different ov5647 cameras, different ribbons and set up 2 Octoprint servers on Pi 3 and 4 to test. Both have same issue and are reproducible. Was working fine before upgrade to 1.9x.

What is the problem?
When I click on the wrench icon for Octoprint settings and close or save settings, webcam loses stream in about 5 seconds. A refresh of the Octoprint browser window will return the webcam stream in Octoprint. Happens on both my  Pi 3 and Pi 4 with Octoprint 1.9x.

Can you recreate it?
Yes, see above. 

Did you try disabling plugins?
Yes, if UI Customizer is disabled or in safe mode, webcam stream is fine. When UI Customizer is active and I go to view Octoprint settings, web stream will go blank displaying  "Webcam stream not loaded" in Octoprint. I exported my UI Customizer settings and cleaned up the plugin data in Plugin Manager, the problem still exists.

Did you remember to update the subject?**
<hr>

**Plugins installed**
- Bed Visualizer[bedlevelvisualizer] v1.1.1
- Creality-2x-temperature-reporting-fix[ender3v2tempfix] v0.0.4
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.28.0
- M73 Progress Plugin[m73progress] v0.2.1
- PrintTimeGenius Plugin[PrintTimeGenius] v2.3.1
- PSU Control[psucontrol] v1.0.6
- Smart Filament Sensor[smartfilamentsensor] v1.2
- Top Temp[toptemp] v0.0.2.3
- **UI Customizer[uicustomizer] v0.1.9.4**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: false
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: false
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: true
- saveAccordions: true
- themeLocal: false

**Software versions**
- OctoPrint 1.9.2
- Python 3.9.2
- OctoPi 1.0.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.8

Please check and reopen if not working - thank you...
