### ISSUE TITLE
Customize to use multiple camera feed

### ISSUE THREAD

**Issue by esrpradeep** [LazeMSS/OctoPrint-UICustomizer#302]
Hello, I'm having an ESP32-Cam used with MultiCam and ESP32 camera plugins. It would be nice to have an add-on feature to bring multiple camera feed windows to the UI. Right now, I have to switch between the cameras or select the plugin tab to get the feed of the default camera (pi camera). 

Btw, now I've the 'classic webcam plugin' disabled. But if I enable 'Multicam plugin' and switch to any other tabs, the UI in the sidebar layout shows 'loading webcam'. is it an error or not supported by this plugin?

![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/65079442/644498f9-7b3a-498c-9e47-8235d4f14517)

![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/65079442/c829c07e-1d7b-4076-b578-34992ae72578)

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.8

Please check and reopen if not working - thank you...

**Comment by esrpradeep** [comment]
Thank you. I checked your fix it is working with Multicam plugin.

Regarding support for Multiple camera, I believe it is possible to create an option for one more window for the camera. In the additional window, one can select if they want two feeds or the same feed on both windows.

Example: For my printer has two cameras feeds one from pi camera (main/default used for time-lapse), and the other one is the esp32-cam. (I have also tried using USB web camera i.e. Logi C270 from the Pi).

![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/65079442/8e644bf9-4e62-49ec-95ba-24da50e48e25)

Use of Multicam plugin..example

![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/65079442/f4f2a2d8-ab9c-4e66-b384-af3488686b8a)

ESP32-cam feed also works in your plugin -- but with just one window.
![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/65079442/35727181-a0ae-47f3-9467-15dd170d4d38)

Waiting for something like multi cam feed windows ( at least two floating windows) feature in the future!

**Comment by esrpradeep** [comment]
Ok, got it. All I know is two streams with two threads to handle the events (handle it as if it is from two sources). Maybe I'm simplifying too much, but it should be possible as you said. I can't ask you more, thanks for fixing the bug and for your support.
