### ISSUE TITLE
Aspectratio is not respected

### ISSUE THREAD

**Issue by fly74** [LazeMSS/OctoPrint-UICustomizer#304]
When use of multicam plugin, only the classic webcam plugin shows the aspect correctly. From multicam it is always 4:3 even if 16:9 is in multicam configured.

https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/38754941/558fd994-d447-4a7f-a525-b339141805d7

**Comment by LazeMSS** [comment]
Does it work then control tab? Basically is the problem isolated to only then "extra" webcam view?

**Comment by fly74** [comment]
The control tab works as expected with all cams.

**Comment by LazeMSS** [comment]
Thanks i will look asap

**Comment by LazeMSS** [comment]
@fly74  please try and add this in custom css in advanced in UI Customizer plugin:
```
.webcam_img_container,.webcam_video_container .webcam_unrotated{
    min-height: initial !important;
}

```

**Comment by fly74** [comment]
@LazeMSS Hey perfect. That works! Can you implement it static?

**Comment by LazeMSS** [comment]
Yes or maybe submit a MR to multicam plugin.

**Comment by LazeMSS** [comment]
Closing as this should be fixed in : https://github.com/mikedmor/OctoPrint_MultiCam/releases/tag/0.4.1
