### ISSUE TITLE
"Top Icons" not displaying

### ISSUE THREAD

**Issue by KrzysztofLang** [LazeMSS/OctoPrint-UICustomizer#305]
## Description
Top icons are not displaying, but can be seen when previewing changes.
Using Firefox, but exact same problem occurred on Chrome.
![!Preview](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/37246634/14a090e2-dfc6-43ac-8009-7fc33b25ab48)
![!Live](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/37246634/1e4530b2-aa6b-4130-859f-4fedbc40e0d1)
<hr>

**Plugins installed**

- PrintTimeGenius Plugin[PrintTimeGenius] v2.3.1
- **UI Customizer[uicustomizer] v0.1.9.8**

**UI Customizer settings/info**
- addWebCamZoom: false
- centerTopIcons: true
- compactMenu: true
- compressTempControls: true
- disableTermInactive: false
- filesFullHeight: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: true
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true
- saveAccordions: false
- themeLocal: false

- New Webcam model: true
- Clasic cam: 

**Software versions**
- OctoPrint 1.9.2
- Python 3.9.2

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

**Comment by LazeMSS** [comment]
Well with no plugins installed the topicons "shown" in preview are actual topicons that are hidden until there is something to display. Like the "Pi support plugin" is only shown if there is an undervoltage problem etc.
