### ISSUE TITLE
[BUG] Fullscreen webcam mode both the maximise and minimize icon

### ISSUE THREAD

**Issue by Draknars** [LazeMSS/OctoPrint-UICustomizer#306]
**Describe the bug**
Fullscreen webcam mode both the maximise and minimize icon

**To Reproduce**
1. What settings are you using in UICustomizer 
2.  Float/Fullscreen webcam -> Fullscreen webcam
3. Go to 'Control' Tab and Click the "Maximise" icon to put in fullscreen
4. In fullscreen, both the minimize and maximise icon overlap
5. If you click accidently on the maximise instead, it will minimize, but you won't be able to put in fullscreen anymore
6. to "Fix it" you need to reload browser

**Expected behavior**
Would expect to only have minimize when in fullscreen

**Screenshots**
Before fullscreen
![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/40360399/ecdf72f9-5656-4a72-908e-bea99e21d9bc)
In fullscreen
![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/40360399/ae974cd9-d485-465c-8f06-4b7c5d5d0d0e)
![image](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/40360399/2748aeb6-547c-4c98-bcf4-e7562eaa0341)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome & Edge latest version

**Additional context**
Mimizing with the correct icon or with using ESC key will not trigger this bug, only when missclicking the maximse icon while in fullscreen.

**Comment by LazeMSS** [comment]
What plugins are you running for webcam? Classic webcam or? Please share a list of enabled plugins.

**Comment by LazeMSS** [comment]
Should be fixed: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.9.9
Please reopen if not.
