### ISSUE TITLE
Slow/Hang on Firefox

### ISSUE THREAD

**Issue by Metathesus** [LazeMSS/OctoPrint-UICustomizer#31]
First, Have to say it's a great plugin but, it is extremely slow/ it hangs with Firefox but no issues with Chrome!

My webcam stream is another Octoprint stream.
Other plugins that I have :
- Bed Visualizer (1.0.0)
- Convert TF to SD (1.0.0)Convert TF to SD in printer responses
- Custom CSS (0.0.1)
- Dashboard (1.16.3) 
- DisplayLayerProgress Plugin (1.24.0)
- FileManager (0.1.4)
- GcodeEditor (0.2.10)
- SpoolManager Plugin (1.2.0)
- Themeify (1.2.2)

My webcam stream is another Octoprint stream, with a different ip adress!

**Comment by LazeMSS** [comment]
And you don't have any problems when my plugin is disabled?
Have you tried disabling the webcam stream totally?

**Comment by Metathesus** [comment]
Yes this problem doesn't occur with your plugin disabled of course.

I've missed to say when Chrome loading it says "!error loading webcam" in the webcam panel but the stream load fine in the control tabs.
![Capture d’écran 2020-12-14 125249](https://user-images.githubusercontent.com/9903113/102078723-b2303c00-3e0b-11eb-9989-4b0eef9258e2.jpg)
And after seconds or minute the videostream appear in your webcam panel.

**If I disable webcam, the panel show "loading webcam" and Octoprint get back is fast behavior.**

**Comment by LazeMSS** [comment]
What is the URL your are using for webcam?

**Comment by Metathesus** [comment]
My octoprint 1.5.1 IP is: 192.168.1.45
Another Octoprint 1.4.x that deliver the stream :
http://192.168.1.40:8080/?action=stream

**Comment by LazeMSS** [comment]
Well is extremely slow in my firefox aswell even when I have UI Customizer disabled - but if you say you have no problems then it might be my installation. I will try and look further.

Are you running windows 10?

**Comment by LazeMSS** [comment]
@Metathesus  please try the latest version: 0.1.1.4 - I found a bug :(

**Comment by Metathesus** [comment]
Seems to be far better (after CTRL+F5 to clear cache)!

Thanks for your fix and all the work you do!

______________
As a suggestion for the file wrapper to better be handled with your plugin, when the file wrapper is in a large central column, I use this css (far from optimized but enough for the moment) with plugin CustomCSS
div.internal{display:none;}
div.uploaded{float:right; margin-top: -15px; margin-right:140px; width:140px;}
div.size{float:right; margin-top:-15px; margin-right: 50px;/*display:none*/}
div.toggleAdditionalData{float:left; margin-right:10px;}
div.scroll-wrapper{height:auto !important;}

You can probably do something to get the same result but in a better way! ;-)

**Comment by LazeMSS** [comment]
Thanks I will look into it asap :)
