### ISSUE TITLE
gcode viewer

### ISSUE THREAD

**Issue by loroff** [LazeMSS/OctoPrint-UICustomizer#310]
bonjours je viens de mettre a jour ui customiser vers la version (0.1.9.9) et un probleme est reapparue la visionneuse gcode ne demarre plus automatiquement ( voir #294 )  Actuellement, je dois passer à l’onglet Gcode pour qu’octoprint analyse le fichier et charge l’aperçu,
je suis sur octoprint 1.9.3
python3.9.2
octopi*1.0.0cam

merci pour votre excellent travail

**Comment by LazeMSS** [comment]
Please write in English.

But basically its a compromise between performance and functionality. So for now its not easy fixable.

**Comment by loroff** [comment]
ok thank you for your reply and for your work
