### ISSUE TITLE
[Suggestion] Extra files options 

### ISSUE THREAD

**Issue by Evan-H-Norton** [LazeMSS/OctoPrint-UICustomizer#317]
Is it possible for this Plugin to add sorting and filtering options for Gcode files?

If not I'd like to set Files Manager plugin as the default on the left Column.

**Comment by LazeMSS** [comment]
Is the gcode file sorting not already there under the wrench symbol?

**Comment by Evan-H-Norton** [comment]
Ah yes, you're right.

Then it would just be nice to move Plugin tabs to the left or right columns
