### ISSUE TITLE
Webcam not placed in right column, even if set to

### ISSUE THREAD

**Issue by fly74** [LazeMSS/OctoPrint-UICustomizer#318]
In OctoPrint 1.10.0rc1 - Python 3.11.5 the webcam is showing at bottom of the middle column. May it is fixable before release of 1.10.

![Screenshot 2024-02-11 103526](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/38754941/0ee179ea-ea32-41cb-89ca-1ac3ab277755)

**Comment by LazeMSS** [comment]
I will look asap

**Comment by LazeMSS** [comment]
Could you try disabling the dashboard plugin?

**Comment by fly74** [comment]
> Could you try disabling the dashboard plugin?

Same with Dashboard disabled.
![Screenshot 2024-02-12 122657](https://github.com/LazeMSS/OctoPrint-UICustomizer/assets/38754941/f97e89d2-4b1b-4290-88e4-389144ddba91)

**Comment by LazeMSS** [comment]
How do you expect it to behave and also please share also your webcam settings

**Comment by foosel** [comment]
Pretty sure this is a duplicate of #315.

**Comment by fly74** [comment]
@foosel You're right.
