### ISSUE TITLE
More a question...

### ISSUE THREAD

**Issue by wrenhal** [LazeMSS/OctoPrint-UICustomizer#326]
Does the UI Customizer save the layout per device via cookies, or is it saved for all devices?

**Comment by LazeMSS** [comment]
The layout - do you mean what is shown where - ie the webcam on the right or left column etc.

Its stored in the Octoprint preferences so its global/all devices.

**Comment by wrenhal** [comment]
Sorry, I meant layout in general.  Chosen theme, etc...  I was wondering if the theme selection could be per device viewing the page.  I have a laptop I use to monitor Octoprint from , but I also have a Dell Tablet I was going to setup next to the printer and I wanted it to have a different theme/ui setup than when I'm on the laptop.  I hope that makes sense.

**Comment by LazeMSS** [comment]
Thats not possible at the moment - the settings are stored as part of Octoprint settings - it would be possible to make it save to the local browser as a kind of overwrite.

**Comment by wrenhal** [comment]
OK.  Thanks
