### ISSUE TITLE
Floating webcam button on secondary webcam loads wrong webcam

### ISSUE THREAD

**Issue by gonzonia** [LazeMSS/OctoPrint-UICustomizer#35]
Using multicam plugin. When I click on the floating webcam button on the top right of the secondary webcam it loads a floating window of the primary webcam. The expected behavior would be the secondary webcam.

**Comment by LazeMSS** [comment]
I will look later tonight

**Comment by LazeMSS** [comment]
Sorry to early to close - will wait for the release 👍

**Comment by LazeMSS** [comment]
Fixed - please confirm/test - if not fixed then reopen :)
https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.6
