### ISSUE TITLE
TouchUI blank screen

### ISSUE THREAD

**Issue by obwielnls** [LazeMSS/OctoPrint-UICustomizer#38]
Using TouchUI I get a blank screen on the /?#printer page.   

![image](https://user-images.githubusercontent.com/76133779/102415506-e9464f00-3fbd-11eb-9199-87d4cfd779e3.png)

**Comment by LazeMSS** [comment]
I don't think touch UI and my plugin is compatible. I don't use it 🙈

**Comment by LazeMSS** [comment]
I can fix it by running:
`
$("#state_wrapper").appendTo('#printer')
$('#files_wrapper').insertAfter('#state_wrapper')
`

Which should be same thing as the TouchUI does:
https://github.com/BillyBlaze/OctoPrint-TouchUI/blob/10bec24adb8ef1af6458d99e85caf12679f2f168/source/js/dom/create/printer.js

I can't fix it - I think your should not mix these plugins.
