### ISSUE TITLE
WebCam rotation

### ISSUE THREAD

**Issue by JoeBeef** [LazeMSS/OctoPrint-UICustomizer#39]
## Description
Hi,

The issue is regarding the webcam picture. I've set it up in the right row of the UI Customizer. The picture look fine but when I clik to get the increased size video, the video appears but is not taking into account the " Rotate webcam 90 degrees counter clockwise " parameter set up in Octoprint for my web cam.

I am running the latest version of Octoprint and updated alle the plugins.

**Plugins installed**
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.24.0
- Enclosure Plugin[enclosure] v4.13.1
- Cura Thumbnails[UltimakerFormatPackage] v0.2.1
- PrusaSlicer Thumbnails[prusaslicerthumbnails] v0.1.3
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- Filament Manager[filamentmanager] v1.6.3
- Preheat Button[preheat] v0.5.1
- **UI Customizer[uicustomizer] v0.1.1.6**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- disableTermInactive: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.2
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.7
Please try and if not fixed then reopen this issue.
