### ISSUE TITLE
All widgets except Main tabs and Webcam disappear after reordering tabs using Dragon Order

### ISSUE THREAD

**Issue by lokety** [LazeMSS/OctoPrint-UICustomizer#4]
I've had https://plugins.octoprint.org/plugins/dragon_order/ installed before installing UI Customizer.

Now whenever I reorder the tabs, all three columns and their widgets disappear, leaving just the header and footer. Then, in the Layout section, Main tabs and Webcam appear under Left row (or should it be called column?) and nothing else.

Clearing data helps to restore all the widgets.

Perhaps a conflict between these two plugins?

**Comment by NovaViper** [comment]
Same here! But for me, Tasmota seems to cause the same issue

**Comment by LazeMSS** [comment]
I will look into but in general these plugins and mine collide because they basically manipulate with the same content inside the viewport. For now you will probally have to disable one of them.

**Comment by NovaViper** [comment]
Tasmota oddly enough doesn't actually change up the viewpoint, not as drastically as Dragon does (it just adds
 a button in the nav bar and a new tab for powering monitoring)

**Comment by NovaViper** [comment]
And even worse, the issue still happens even though I have Tasmota turned off.. so im not sure what it could be anymore <_>

**Comment by LazeMSS** [comment]
> And even worse, the issue still happens even though I have Tasmota turned off.. so im not sure what it could be anymore <_>
> 
> --edit--
> I turned off every plugin except UI Customizer and the main tabs are still gone.. what do I do now??

Try clean the data of the UI Customizer and the set it up again - it might have broken something.
To cleanup find the UI Customizer in the Plugin manager and press the eraser icon: https://fontawesome.com/icons/eraser?style=solid

 Is it still a problem after cleanup?

**Comment by LMS0815** [comment]
Looks like: https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/8

**Comment by LazeMSS** [comment]
I figured it out - it was because of the fac that other plugins saved data without showing the UI - now my code checks for this. This has been fixed in the 0.1.0.0 release: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.0.0
