### ISSUE TITLE
Request - Dark theme for "Improve mobile/responsive" option

### ISSUE THREAD

**Issue by Lecl0ne** [LazeMSS/OctoPrint-UICustomizer#42]
A dark theme would be so appreciated ! :)

![Dark theme](https://user-images.githubusercontent.com/42405376/102878120-0f4d7280-4448-11eb-98c5-eee4413d723c.png)

**Comment by LazeMSS** [comment]
I will add themes soon (tm)

**Comment by Lecl0ne** [comment]
Same request for th footer :)

![Black footer](https://user-images.githubusercontent.com/42405376/102879766-a4516b00-444a-11eb-84aa-f289d29b06d5.png)

**Comment by LazeMSS** [comment]
Fixed in 0.1.1.9(https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.9)
- please check and reopen/comment if not working as expected.
