### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by mikeradom** [LazeMSS/OctoPrint-UICustomizer#44]
## Description
JUST SEMANTICS...
... but confused me for a while.    "Layout" has three sections - _Left Row_, _Center Row_, and _Right Row_ .  Those are columns, not rows.   Would be easier on my brain if you changed that - thank you!  :-)
<hr>

**Plugins installed**
- Detailed Progress[detailedprogress] v0.2.6
- DisplayProgress[displayprogress] v0.1.3
- SpoolManager Plugin[SpoolManager] v1.2.0
- TP-Link Smartplug[tplinksmartplug] v0.9.26
- **UI Customizer[uicustomizer] v0.1.1.8**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- disableTermInactive: false
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- hideGraphBackground: false
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.2
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.60

**Comment by LazeMSS** [comment]
Fixed in 0.1.1.9(https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.9)
- please check and reopen/comment if not working as expected.
