### ISSUE TITLE
Floating Webcam doesn't follow "flip webcam" settings

### ISSUE THREAD

**Issue by Whichonespink11** [LazeMSS/OctoPrint-UICustomizer#5]
I have the webcam set up on the right side of the page. When I click on the arrows to access the larger floating webcam, it displays upside down and backward (the default orientation of my camera). When it is tucked into the right display panel, everything displays with the proper settings. It is only when I expand the webcam that it ignores the webcam settings. 
In Octoprint Settings->Features->Webcam & Timelapse, I have the "flip webcam horizontally" and "flip webcam vertically" checked.
Thank you!!

**Comment by LazeMSS** [comment]
Will be fixed in next release: https://github.com/LazeMSS/OctoPrint-UICustomizer/commit/28828d90b2fb6097da513bfd8989f936a218dcbd
