### ISSUE TITLE
Compatibility issue with SimpleEmergencyStop

### ISSUE THREAD

**Issue by Sebclem** [LazeMSS/OctoPrint-UICustomizer#51]
Hi,
I'm the developer of [SimpleEmergencyStop](https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop). It seem that we have a compatibility issue.

The navbar button seam to be unaligned when your plugin is installed:
Normal disposition: 
![image](https://user-images.githubusercontent.com/23737709/103550299-fcf02180-4ea8-11eb-9c3a-5e77fce92a6b.png)
With your plugin installed:
![image](https://user-images.githubusercontent.com/23737709/103550490-42acea00-4ea9-11eb-86a0-ed1bc796b118.png)

I'm opening an issue here to know if I need to do something to make my plugin compatible with UiCustomizer or if the cards is all in your hands.

Let me know if you need more informations.
Opened issue on my repo : https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop/issues/18

**Comment by LazeMSS** [comment]
@Sebclem i will look - btw. to a quick look at your plugin - don't think you need to include font awesome 5 anymore :)

**Comment by Sebclem** [comment]
Oh thank ! I see the update PR ! Perfect !

**Comment by LazeMSS** [comment]
I think the error is on your side - you are including a "link" directly in the header - will update in your issue and close this
