### ISSUE TITLE
Problem displaying TempTab in mobile mode

### ISSUE THREAD

**Issue by Merhim** [LazeMSS/OctoPrint-UICustomizer#56]
Hi Laze,
I have some issue with the visualization of the Temperature Tab using the mobile phone version.

Thanks and geat job :thumbsup:

![Screenshot_2021-01-05-11-27-07-28](https://user-images.githubusercontent.com/76015321/103639456-accb9a80-4f4e-11eb-8c32-8cb3d9e46287.jpg)

**Comment by LazeMSS** [comment]
The screen is 300 px wide - but whats the probelm - input fields problems?
