### ISSUE TITLE
Enhancement request - themes (dark theme)

### ISSUE THREAD

**Issue by turbatus** [LazeMSS/OctoPrint-UICustomizer#61]
Hi, I really enjoy your plugin. I used to use Themeify, but your plugin complains about it. Is there a plan to allow theming? Particularly, a dark theme? Octoprint with UICustomizer in a dark room (or during night) with a white background is stressful for the eyes.
Thanks.

**Comment by LazeMSS** [comment]
Its impleted in the latest version - please update.

**Comment by LazeMSS** [comment]
My plugin only complains if you are using the top bar icon mods - please update and report back on this issue if not fixed with latest version
