### ISSUE TITLE
Double background

### ISSUE THREAD

**Issue by Lecl0ne** [LazeMSS/OctoPrint-UICustomizer#67]
It looks like the background is kind of double (on every tab), with one rounded and the other not.
Did you try disabling plugins? Yes, it solves the problem
<hr>

**Plugins installed**
- ProgressBasedOntime Plugin[ProgressBasedOnTime] v0.1.6
- Friendly Neighborhood Beeper[FriendlyBeeper] v0.4.0
- Marlin GCode Documentation[marlingcodedocumentation] v0.11.0
- Fullscreen Plugin[fullscreen] v0.0.6
- Auto Terminal Input[AutoTerminalInput] v0.1.0
- Themeify[themeify] v1.2.2
- Autoscroll[autoscroll] v0.0.3
- Terminal Messaging[terminalmessaging] v0.1.0
- **UI Customizer[uicustomizer] v0.1.2.4**
- Autoselect Plugin[autoselect] v0.3.0
- Autologin Configuration[autologin_config] v0.2.0
- M117NavBar[M117NavBar] v0.1.1
- Printoid Plugin[printoid] v1.0.2
- Bed Visualizer[bedlevelvisualizer] v1.0.0
- SetAndWait[setandwait] v0.0.1
- Progress Title[progress_title] v0.1.1
- Detailed Progress[detailedprogress] v0.2.6
- GCODE System Commands[gcodesystemcommands] v1.0.1
- Cura Thumbnails[UltimakerFormatPackage] v0.2.1
- Preheat Button[preheat] v0.5.1
- Multi Line Terminal[multilineterminal] v0.1.5
- SpoolManager Plugin[SpoolManager] v1.2.0
- Cost Estimation[costestimation] v3.1.0
- Tempsgraph Plugin[tempsgraph] v0.3.6
- Active Filters Extended[active_filters_extended] v0.1.0
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- Arc-Welder[arc_welder] v1.0.0+u.bb71e8f
- Octolapse[octolapse] v0.4.1

**UI Customizer settings**
- addWebCamZoom: false
- centerTopIcons: true
- compactMenu: true
- compressTempControls: false
- disableTermInactive: true
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: true
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.2
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75

![Double](https://user-images.githubusercontent.com/42405376/104316450-c46dca80-54dc-11eb-8860-fea1f3026eb9.png)

**Comment by LazeMSS** [comment]
Its related to a theme I think - what theme are you using?

**Comment by Lecl0ne** [comment]
Discoranged. If I disable this theme, it solves the problem. If i turn it back on, it's here again...

**Comment by LazeMSS** [comment]
I will look

**Comment by LazeMSS** [comment]
Fixed in next release

**Comment by LazeMSS** [comment]
Closing - should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.2.5
If anyone disagrees please reopen this issue :)

**Comment by Lecl0ne** [comment]
Double background solved. But the shadow is kind of FAT, comparing to the normal one.
![Shadow](https://user-images.githubusercontent.com/42405376/105035136-cd214c00-5a5a-11eb-9a7f-3290ba022c97.png)

**Comment by LazeMSS** [comment]
Ahh will look
