### ISSUE TITLE
Improvement Request - Save gcode zoom level

### ISSUE THREAD

**Issue by screwyluie** [LazeMSS/OctoPrint-UICustomizer#69]
just as the title says, it would be nice if the zoom level of the gcode preview was saved. And honestly zoom level 4 it's pretty useless imo would rather see it start with 3 and add a step between 1 and 2, but that's just me. I would be 100 % pleased with this plugin if it just remembered the zoom level

**Comment by LazeMSS** [comment]
Will add an extra and try and make it save the settings

**Comment by LazeMSS** [comment]
Added in next release

**Comment by LazeMSS** [comment]
Closing - should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.2.5
If anyone disagrees please reopen this issue :)
