### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by Ruissilva** [LazeMSS/OctoPrint-UICustomizer#71]
## Description
Hi.
These images show thu UI Customizer. In the computer its ok, but in the phone its wierd. Any ideia how i can fix this?

![PC](https://user-images.githubusercontent.com/77809758/105438355-bcd7bf80-5c5a-11eb-8a66-352cad7cf81f.png)
![Phone](https://user-images.githubusercontent.com/77809758/105438358-bd705600-5c5a-11eb-97e2-4f614273b3b9.jpg)

**Plugins installed**
- Access Anywhere - The Spaghetti Detective[thespaghettidetective] v1.4.7
- Autoscroll[autoscroll] v0.0.3
- Autoselect Plugin[autoselect] v0.3.0
- Backup Scheduler[backupscheduler] v0.0.4
- Bed Visualizer[bedlevelvisualizer] v1.0.0
- Cancel Objects[cancelobject] v0.4.4
- Cura Thumbnails[UltimakerFormatPackage] v0.2.1
- Custom Background[custombackground] v1.0.0
- Custom Control Editor[customControl] v0.2.2
- DisplayLayerProgress Plugin[DisplayLayerProgress] v1.24.0
- Enclosure Plugin[enclosure] v4.13.1
- Filament Manager[filamentmanager] v1.6.3
- Filament Sensors Revolutions[filamentrevolutions] v1.0.0
- Firmware Updater[firmwareupdater] v1.7.7
- Floating Navbar[floatingnavbar] v0.3.4
- GcodeEditor[GcodeEditor] v0.2.10
- HeaterTimeout[HeaterTimeout] v0.0.3
- Multi Colors[multi_colors] v1.0.17
- Navbar Temperature Plugin[navbartemp] v0.14
- Octolapse[octolapse] v0.4.1
- OctoLight[octolight] v0.1.0
- Preheat Button[preheat] v0.5.1
- PrintJobHistory[PrintJobHistory] v1.10.0
- Printoid Plugin[printoid] v1.0.2
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- PSU Control[psucontrol] v0.1.10
- Resource Monitor[resource_monitor] v0.2.8
- Simple Emergency Stop[simpleemergencystop] v1.0.4
- SlicerSettingsTab[SlicerSettingsTab] v1.0.3
- Tab Order[taborder] v0.5.12
- Telegram Notifications[telegram] v1.6.2
- TemperatureFailsafe[TemperatureFailsafe] v0.2.3
- Themeify[themeify] v1.2.2
- TimeToFilament Plugin[TimeToFilament] v1.2.1
- **UI Customizer[uicustomizer] v0.1.2.5**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: false
- compactMenu: true
- compressTempControls: true
- disableTermInactive: true
- fixedFooter: false
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: false
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.3
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**Comment by LazeMSS** [comment]
I'm working on a solution for this - but basically there is not room for the icons.

**Comment by LazeMSS** [comment]
Fixed in latest release - its not perfect but working

**Comment by Ruissilva** [comment]
Hello LazeMSS, thanks for the help.
I installed the latest update of the plugin, and im sorry to say nothing changed.

**Comment by LazeMSS** [comment]
Can you post a screenshot? And what is the problem. The icons or the menu?

**Comment by Ruissilva** [comment]
Ok, right now i have installed UI Customizer (0.1.2.8). 

![PC](https://user-images.githubusercontent.com/77809758/107118858-8cf40300-687b-11eb-9b9b-7e50d264985a.png)

![Screenshot_20210206_125354_com android chrome](https://user-images.githubusercontent.com/77809758/107118865-98dfc500-687b-11eb-9a2d-66b19d6b8e0f.jpg)

One thing that i whould like to see in this plugin is the ability to chose which icons to show, for example, with some toggle buttons. I put an image below has a example. 

![example](https://user-images.githubusercontent.com/77809758/107118897-d3e1f880-687b-11eb-93c0-78b98c3aa0d9.png)

best of luck

**Comment by LazeMSS** [comment]
Okay - i just tested - i can see the same problems.

Btw. good idea with an option to disable a top icon

**Comment by LazeMSS** [comment]
Should be fixed in the latest release - please try again:
https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.0

Reopen if not fixed - thanks.
