### ISSUE TITLE
UI Customizer messes up Edit Spool popup for SpoolManager

### ISSUE THREAD

**Issue by lightmaster** [LazeMSS/OctoPrint-UICustomizer#73]
When UI Customizer is enabled, it negatively effects the [SpoolManager](https://github.com/OllisGit/OctoPrint-SpoolManager) Plugin. See OllisGit/OctoPrint-SpoolManager#112 for screenshots.

The edit spool popup of that page is supposed to be 2 columns, however when UI Customizer is enabled, it becomes 1 long column and the text box on the page disappears.

**Comment by LazeMSS** [comment]
Not fixing - UI Customizer basically just add bootstrap standard responsive css and the HTML in the spoolmanager is not bootstrap compliant and this causes layout issues. Me fixing this will probally just break something instead. I have posted a guide on how to fix it on the SpoolManager issue
