### ISSUE TITLE
UI incorrect output

### ISSUE THREAD

**Issue by Homerist** [LazeMSS/OctoPrint-UICustomizer#74]
after 10 Minutes in print some screen failure. See Screenshot

After Reboot the Pi it works for about 10 minutes and then again.

![octoprint](https://user-images.githubusercontent.com/78500090/106787831-76b62f00-6650-11eb-9195-5837f2a2fe94.PNG)

Some Other Plugins that i used:

themeify
discordremote
toptemp

**Comment by LazeMSS** [comment]
You mean the gcode viewer?

Does it happen with all gcode files or just one certain?

**Comment by Homerist** [comment]
with all, the same is at the temperature tab too

**Comment by LazeMSS** [comment]
Have you tried disabling UI customizer and see if the problem is still there?

**Comment by Homerist** [comment]
Yes, i tried it, after disabling UI customizer is all working normal

**Comment by LazeMSS** [comment]
UI Customizer should not affect anything related to the temp graph and the bugs you have shown looks more like a rendering issue in a browser.

**Comment by Homerist** [comment]
Please close this, i tried this on a other Pi and the same. But on a other browser it works. 

Sorry for that

**Comment by LazeMSS** [comment]
Thanks for checking :)
