### ISSUE TITLE
Can't update to 0.1.2.6

### ISSUE THREAD

**Issue by denkyem** [LazeMSS/OctoPrint-UICustomizer#77]
Every time I try to update the plugin, it installs, octoprint restarts but then I reveice the notification again that some update is available.

I believe the issue is in setup.py file.

plugin_version = "0.1.2.5"

It should be 0.1.2.6, right?

**Comment by denkyem** [comment]
I change the plugin_version in setup.py and force the update using command line.
It's updated now.

**Comment by LazeMSS** [comment]
Fixed now - a bit rushed release. I dont get enough sleep :/
