### ISSUE TITLE
Top Bar Dropdown of Enclosure Plugin doesn't work since Update to V0.1.2.7

### ISSUE THREAD

**Issue by diedder** [LazeMSS/OctoPrint-UICustomizer#79]
since updating to the latest version the pulldowns of the ecnclosure plugin doesn't work anymore... reminds me of #49 but in this case it cannot be fixed by reload the page or deactivating the fixed topbar option.

![image](https://user-images.githubusercontent.com/25912001/106918869-e3413480-6709-11eb-900b-4198a284184b.png)

**Comment by LazeMSS** [comment]
I will look

**Comment by LazeMSS** [comment]
Fixed in 0.1.2.8
