### ISSUE TITLE
Webcam portrait mode support

### ISSUE THREAD

**Issue by realmadridsi** [LazeMSS/OctoPrint-UICustomizer#8]
Thank you for this amazing plugin!

I have my webcam in portrait mode and it seems like it's not supported right now. The alignment of the video feed is not right for the webcam preview, it is overlapping the progress bar and the text.
![webcam preview](https://user-images.githubusercontent.com/50031259/100864112-d861ed80-3495-11eb-892a-e998b6c97d88.png)

**Comment by LazeMSS** [comment]
Is fixed/working in next release

**Comment by realmadridsi** [comment]
Thanks a lot!

**Comment by LazeMSS** [comment]
Closing - please reopen if not fixed in next release
