### ISSUE TITLE
Spool manager window deformed/not complete

### ISSUE THREAD

**Issue by cicinovec** [LazeMSS/OctoPrint-UICustomizer#81]
## Description
**Spool manager window not complete
When opening the spool parameters window it is not complete, cut by grey area at bottom.
Without customizer is OK
Checked with 3 types of browsers, no change**

![Spool_manager](https://user-images.githubusercontent.com/33634908/107183696-8ed6d700-69df-11eb-97e2-5a7493bb67cb.png)
<hr>

**Plugins installed**
- Access Anywhere - The Spaghetti Detective[thespaghettidetective] v1.5.1
- Autologin Configuration[autologin_config] v0.2.0
- Autoscroll[autoscroll] v0.0.3
- Backup Scheduler[backupscheduler] v0.0.4
- BLTouch Plugin[BLTouch] v0.3.4
- Custom Control Editor[customControl] v0.2.2
- Detailed Progress[detailedprogress] v0.2.7
- DisplayZ[displayz] v0.2.0
- LightsOut[lightsout] v0.1.2
- MultiCam[multicam] v0.2.8
- Navbar Temperature Plugin[navbartemp] v0.14
- OctoKlipper[klipper] v0.3.2
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- SpoolManager Plugin[SpoolManager] v1.3.3
- **UI Customizer[uicustomizer] v0.1.2.8**

**UI Customizer settings**
- addWebCamZoom: true
- centerTopIcons: true
- compactMenu: true
- compressTempControls: false
- disableTermInactive: false
- fixedFooter: true
- fixedHeader: true
- fluidLayout: true
- gcodeFullWidth: false
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: false
- responsiveMode: true

**Software versions**
- OctoPrint 1.5.3
- Python 3.7.3
- OctoPi 0.18.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36

**Comment by LazeMSS** [comment]
https://github.com/OllisGit/OctoPrint-SpoolManager/issues/112

Discuss here :)
