### ISSUE TITLE
! Error loading webcam

### ISSUE THREAD

**Issue by theo78825** [LazeMSS/OctoPrint-UICustomizer#82]
This seems to affect the Safari web browser in particular. When loading the Octoprint page, an error saying "! Error loading webcam" displays where the webcam view should be. By going to the "Control" tab, there are no problems viewing the stream there. After a few minutes, the webcam view on the main page eventually loads.
<img width="633" alt="Screen Shot 2021-02-13 at 9 05 29 PM" src="https://user-images.githubusercontent.com/12882244/107866460-4ab06000-6e3f-11eb-9972-6efcd81199a5.png">
<img width="664" alt="Screen Shot 2021-02-13 at 9 00 43 PM" src="https://user-images.githubusercontent.com/12882244/107866461-4be18d00-6e3f-11eb-9ed7-ef41861f6f87.png">

**Comment by LazeMSS** [comment]
I can't reproduce this - I dont have a stable mac for testing it - does the developer console of Safari browser say anything. It might be handling/reloading of the webcam feeds when the browser/tab it out of "focus".

Can you try and test a bit more/explain - does it only happen in Safari?

**Comment by theo78825** [comment]
Will take a look and report back!

**Comment by theo78825** [comment]
Here are the errors in the developer console. When I switch to a different tab and come back, it seems to load immediately. 
<img width="1280" alt="Screen Shot 2021-02-18 at 7 38 25 PM" src="https://user-images.githubusercontent.com/12882244/108440659-8d987c00-7221-11eb-87b0-201a376a141b.png">

**Comment by LazeMSS** [comment]
Okay - strange. I will try and fire up my old mac and have a look in the weekend.

**Comment by LazeMSS** [comment]
I can't recreate in my safari 13.1.3 (OS: Catalina 10.15.7)

Do you use HLS or normal mjpeg?

**Comment by theo78825** [comment]
I’m not sure, sorry. I believe mjpeg.

**Comment by bergdahl** [comment]
I see the same problem on my Mac running Chrome. I have 2 OCtopi instances, one running a local webcam and the other running a networks tream. Same problem on both. When I load the page the video is not show, If I switch to another tab and back it displays normally. Chrome reports Cancelled on load though. 

<img width="996" alt="Skarmavbild_2021-02-20_kl _22 33 40" src="https://user-images.githubusercontent.com/2373335/108783076-0e7ead00-756d-11eb-966b-ae9009b6891c.png">

**Comment by bergdahl** [comment]
This is the result of loading the main screen for the instance using an external stream. (Chrome)
<img width="1321" alt="Skärmavbild 2021-02-23 kl  00 45 35" src="https://user-images.githubusercontent.com/2373335/108784963-c95c7a00-7570-11eb-80f8-ba9fb095804f.png">

This is the result of loading the main screen for the instance using a local USB webcam. (Safari)
<img width="1118" alt="Skärmavbild 2021-02-23 kl  00 52 01" src="https://user-images.githubusercontent.com/2373335/108785277-61f2fa00-7571-11eb-9e9f-6eb6287a9b09.png">

**Comment by LazeMSS** [comment]
Whare are the formats of the streams ?
Can I have a url for the external stream so I can try it on my version.

I have tried in both firefox, chrome, and safari on my own installation - and no problems. I'm using the "standard" webcam option of octopi using mjpeg streamer

**Comment by bergdahl** [comment]
Internal stream is the bundled Octopi streamer, so using mjpeg-streamer. External stream is mjpeg,url is not available outside my LAN.

**Comment by LazeMSS** [comment]
Okay - I have tried with both - I'm recoding the entire webcam part - I have learned alot since I made that part so maybe the new stuff can fix it - I post a test link for you guys as soon its ready.

**Comment by LazeMSS** [comment]
Damm its hard when I can't recreate the error - @bergdahl would it be possible with a remote teamviewer etc. so I could have a look.

"I can also report that the webcam is loading if I check "Hide main camera". - does this mean everything is working fine when this is checked?

**Comment by bergdahl** [comment]
Yes, it works as expected if "Hide main camera" is checked.

**Comment by LazeMSS** [comment]
@bergdahl  and  @theo78825  please try the develop and confirm if its working or not:

```
Open Settings, then click Plugin Manager
At the bottom click "Get more.."
In the input field below "... from URL" paste in: https://github.com/LazeMSS/OctoPrint-UICustomizer/archive/develop.zip
Click Install
```

**Comment by bergdahl** [comment]
Confirmed.

**Comment by theo78825** [comment]
Nice job! Looks good on my end!
