### ISSUE TITLE
Theme question

### ISSUE THREAD

**Issue by Poeschl** [LazeMSS/OctoPrint-UICustomizer#88]
How would you like new themes to be contributed?
I have already a [PR open on the Themeify-Plugin ](https://github.com/Birkbjo/OctoPrint-Themeify/pull/110) for some dark themes with colored accents and would like to include it here as well.

Are you expecting the styles as less files or css ones? I'm also thinking to combine the themes to one with a user customizable accent color.

**Comment by LazeMSS** [comment]
Css - I making a seperate repro for all the themes files where it can be included. Will release this soon (tm)

**Comment by Poeschl** [comment]
:+1: Take your time. Its ready when its ready
