### ISSUE TITLE
Unwanted relod of CamWidget if Active Filters Extended (0.1.0) is installed

### ISSUE THREAD

**Issue by LMS0815** [LazeMSS/OctoPrint-UICustomizer#9]
If you have the _[Active Filters Extended (0.1.0)](https://github.com/jneilliii/OctoPrint-ActiveFiltersExtended)_ plugin installed, 
on every filter change at the terminal window the webcam widget is reset/reloaded .

**Comment by LazeMSS** [comment]
HLS or normal webcam?

**Comment by LMS0815** [comment]
If normal means PiCam, no.

Stream URL: `http://192.168.1.250:8080/mjpg/I4/video.mjpg?fps=10&q=50&cache=1&decode=1`

Disabling the plugin helps. 
I assume it has something to do with the plugin saving/changing OctoPrint configuration `config.yaml`.

**Comment by LazeMSS** [comment]
yes correct - will look now 👍

**Comment by LMS0815** [comment]
Add:

Occasionally the whole UI is corrupted (disappears) if the _Active Filters Extended_ is enabled.
Means only the header line is shown. As soon your update is available, I'll give it a test regarding this finding.
