### ISSUE TITLE
Resize of files section

### ISSUE THREAD

**Issue by Spooky-Wookie** [LazeMSS/OctoPrint-UICustomizer#90]
First things first:
Thx for this great piece of software...
But:
is the any possibility to resize the files section?
Actual it shows only a small overview of the files uploaded to OPi.
<img width="442" alt="files1" src="https://user-images.githubusercontent.com/55342541/108593212-cbf18080-7372-11eb-99a5-140cf43bb872.png">
About 50% of the column is empty (at least in my case).
Would love to see an option to fill up the emty space with a bigger files-section view.
<img width="260" alt="files2" src="https://user-images.githubusercontent.com/55342541/108593277-1b37b100-7373-11eb-8406-4c73e2c2ac20.png">

**Comment by LazeMSS** [comment]
Great idea :)

**Comment by LazeMSS** [comment]
Added in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.2

Closing - please reopen if not working/fixed as expected
