### ISSUE TITLE
Top Icon for Firmware Updater not working correctly

### ISSUE THREAD

**Issue by Christoph512** [LazeMSS/OctoPrint-UICustomizer#95]
If i press the Top Icon for Firmware Updater i get the last opened settings page and not the page for Firmware Updater.

![grafik](https://user-images.githubusercontent.com/71673435/108636401-4f9b9200-7485-11eb-931e-7cbc2e72d913.png)

**Comment by LazeMSS** [comment]
And this does not happen when disabling UI customizer?

What have you tried?

**Comment by Christoph512** [comment]
When UI Customizer is disabled, it opens the settings page for Firmware Updater, even if i was before on another settings page.

**Comment by LazeMSS** [comment]
This is fixed in the next release - please test/try by following the below guide:

Open Settings, then click Plugin Manager
At the bottom click "Get more.."
In the input field below "... from URL" paste in: https://github.com/LazeMSS/OctoPrint-UICustomizer/archive/develop.zip
Click Install

**Comment by Christoph512** [comment]
I tested it along your guide, now its working. Thank you very much! 👍

**Comment by LazeMSS** [comment]
Keeping it open until public released :)

**Comment by LazeMSS** [comment]
Now released and fixed 👍
