### ISSUE TITLE
Latest bug release not pushed out yet? 

### ISSUE THREAD

**Issue by MrDragon420** [LazeMSS/OctoPrint-UICustomizer#98]
New user and i saw you did a bug fix but i dont see the update

**Comment by LazeMSS** [comment]
There can be a bit of delay before the update is pushed out to everybody

**Comment by LazeMSS** [comment]
Wait a couple of hours...

**Comment by lightmaster** [comment]
@MrDragon420 On the `Software Updates` settings page, you can click the `Advanced options ▼` button that's under `Check for Updates`, and then click the newly unhidden `Force Check for Updates` button to make sure you're getting the latest version. Not really sure why that's the the default behavior for `Check for Updates`....

**Comment by LazeMSS** [comment]
Closing now

**Comment by MrDragon420** [comment]
I still do not get the updates?

**Comment by LazeMSS** [comment]
@MrDragon420 did you get it?
