### ISSUE TITLE
[Bug] Themed compressed file list hides some dropdown settings

### ISSUE THREAD

**Issue by lightmaster** [LazeMSS/OctoPrint-UICustomizer#99]
When using a theme which compresses the file list so it doesn't show the full file list if it's empty, this causes the bottom of the drop down box to be hidden when the file list is the last item in a column. In my screenshot, the `Hide successfully printed files` option is inaccessible. I can go into the Inspect window and delete the HTML for the footer bar, and then I can see and interact with this last option again.

![screenshot 3](https://user-images.githubusercontent.com/5307827/109088764-0eea8580-76de-11eb-844c-6de13f5361a1.jpg)

**Comment by LazeMSS** [comment]
What themes makes the file folder that small?

**Comment by LazeMSS** [comment]
Fixed in develop

**Comment by lightmaster** [comment]
Installing it again to test now.

**Comment by lightmaster** [comment]
Well, it does show up now, but I thought the compressed empty file list was a feature, not a bug. IMO, it'd be nicer to have the list compressed when empty/low, and when menu is opened, there's invisible padding added to the outside of the dropdown menu such that it forces the page to scroll down lower.

**Comment by lightmaster** [comment]
my temp fix was custom CSS

```CSS
.accordion-heading .dropdown-menu {
  padding: 5px 0 40px 0;
}
```
However that creates a visible padding on the bottom of the dropdown menu. idk much about CSS and couldn't figure out what to do to make invisible padding.

**Comment by LazeMSS** [comment]
@lightmaster  feel free to make these changes and do a pull request.

**Comment by LazeMSS** [comment]
Ohh and I made it to big - fixed now

**Comment by lightmaster** [comment]
Thankfully the `min-height: 70px` looks good to me, cuz I've hit the extent of my knowledge of CSS and unable to create a transparent padding that doesn't jack up the menu.

With the new height, I am unable to get the menu to sink below the foot now.

**Comment by LazeMSS** [comment]
Should be fixed in: https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.5.4
Please reopen/comment it not 😄
